### PR TITLE
Fixes segfault for when initializing Target list. 

### LINKED ISSUE #1093: Segfault when cds/rds connections fail on startup
Config and backtrace here:
https://gist.github.com/mattwoodyard/aedc9cd486cb626626fa6a2b36f7bbc4

It appears to be related to name resolution - using a resolvable name in the config yields a running envoy (albeit obviously not working).

### PR DESCRIPTION
**Pull request by ccaraman**
Fixes #1093 

When initializing the targets, it is possible to remove the current item. The fix is to update the iterator pointer before initializing the target.

### CODE REVIEW

File: source/server/server.cc [hunk 1]
```diff
@@ -41,7 +41,11 @@ void InitManagerImpl::initialize(std::function<void()> callback) {
...
     state_ = State::Initializing;
-    for (auto target : targets_) {
+    // Target::initialize(...) method can modify the list to remove the item currently
+    // being initialized, so we increment the iterator before calling initialize.
+    for (auto iter = targets_.begin(); iter != targets_.end();) {
+      Init::Target* target = *iter;
+      ++iter;
       target->initialize([this, target]() -> void {
         ASSERT(std::find(targets_.begin(), targets_.end(), target) != targets_.end());
         targets_.remove(target);
```
Comment (htuch) [inline source/server/server.cc]: Nice catch. Do you have any references (for my education) pointing to where it is safe to use `remove` and `list` increment? I can find plenty of references to the combination of `erase` and increment being a safe combination. I don't know much about STL guarantees here.

Comment (mattklein123) [inline source/server/server.cc]: "Addition, removal and moving the elements within the list or across several lists does not invalidate the iterators or references. An iterator is invalidated only when the corresponding element is deleted."

http://en.cppreference.com/w/cpp/container/list

Comment (dnoe) [inline source/server/server.cc]: This requirement is why the STL lists do the somewhat inefficient thing of making the allocated list nodes contain a pointer to the separately allocated content rather than an implementation like Boost's "intrusive" lists.

**Comment by mattklein123** [comment]
@ccaraman is going to be out for a few days so I fixed the compiler issue so we can get this fix in.
