### PR TITLE
Backtrace on fatal signals.

### LINKED ISSUE #487: Backtrace support in debug builds
Add something like https://github.com/bombela/backward-cpp to the build (at least for debug builds) and enable dumping a stack trace on crash with a std::terminate_handler.

### PR DESCRIPTION
**Pull request by dnoe**
This commit adds signal handlers into main.cc, or any smaller scope as
desired.  For any fatal signals a backtrace is logged and then the
signal is re-raised to continue with the default behavior.

The backtrace logging and script are modified slightly to support all
objects found and not make assumptions about the first stack frame being
in the binary we care about. This is needed for reasonable output in the
case of abort() or any fatal signal like SEGV that crops up inside a
library function we call.

Fixes #487

### CODE REVIEW

**Comment by dnoe** [comment]
@htuch

File: source/exe/signal_action.cc [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+  raise(sig);
+}
+
+void SignalAction::InstallSigHandlers() {
+  stack_t stack;
+  stack.ss_sp = altstack_.get();
+  stack.ss_size = ALTSTACK_SIZE;
+  stack.ss_flags = 0;
+
+  if (sigaltstack(&stack, nullptr) < 0) {
```
Comment (htuch) [inline source/exe/signal_action.cc]: Prefer `RELEASE_ASSERT` per https://github.com/lyft/envoy/pull/854 for now. If `sigaltstack` fails, something terrible has happened.

Comment (htuch) [inline source/exe/signal_action.cc]: You might want to zero the stack before setting it here. Best to not have random heap stuff sitting on a stack for security reasons.

File: source/exe/signal_action.cc [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+      // Auto backtraces won't work, but we can still start up.
+      std::cerr << "Nonfatal error: Failed to set up signal action for signal " << sig << ": "
+                << strerror(errno) << std::endl;
+    }
+  }
+}
+
+void SignalAction::RemoveSigHandlers() const {
+  for (const auto& sig : FATAL_SIGS) {
+    signal(sig, SIG_DFL);
```
Comment (htuch) [inline source/exe/signal_action.cc]: Since you're doing RAII, how about remembering the `oldact` returned by `sigaction` above and restoring it? Not that it matters much here, but there's something nice about the symmetry there and RAII.

File: source/exe/signal_action.cc [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+              << std::endl;
+  }
+
+  for (const auto& sig : FATAL_SIGS) {
+    struct sigaction saction;
+    std::memset(&saction, 0, sizeof(saction));
+    sigemptyset(&saction.sa_mask);
+    saction.sa_flags = (SA_SIGINFO | SA_ONSTACK | SA_RESETHAND | SA_NODEFER);
+    saction.sa_sigaction = SigHandler;
+    if (sigaction(sig, &saction, nullptr) < 0) {
```
Comment (htuch) [inline source/exe/signal_action.cc]: Same here with `RELEASE_ASSERT`

**Comment by mattklein123** [comment]
Quick drive by comment: can we put even the installation of the extra signals behind some build flag? I don't want to have them installed in our release builds.

File: source/exe/signal_action.cc [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+void SignalAction::SigHandler(int sig, siginfo_t* info, void* context) {
+  void* error_pc = 0;
+
+  const ucontext_t* ucontext = reinterpret_cast<const ucontext_t*>(context);
+  if (ucontext != nullptr) {
+#ifdef REG_RIP
+    // x86_64
+    error_pc = reinterpret_cast<void*>(ucontext->uc_mcontext.gregs[REG_RIP]);
+#elif defined(REG_EIP)
+    // x86 Classic - not tested
```
Comment (dnoe) [inline source/exe/signal_action.cc]: Agree, I will do that until/unless we have a way of testing them.

File: source/exe/signal_action.h [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+  /**
+   * Remove all signal handlers.
+   *
+   * Must be executed before the alt stack memory goes away.
+   *
+   * Signal handlers will be reset to the default, NOT back to any signal
+   * handler existing before InstallSigHandlers().
+   */
+  void RemoveSigHandlers() const;
+  std::unique_ptr<char[]> altstack_;
```
Comment (dnoe) [inline source/exe/signal_action.h]: I think mmap of two pages, with the second page mprotect'd as a guard page is a great solution assuming there aren't any technical blockers to doing it that way.

File: source/exe/signal_action.cc (hunk 1 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: Looks like mmap with MAP_ANONYMOUS will map a zero'd page, so doing that will address this as well.

File: source/exe/signal_action.cc (hunk 2 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: Sure, I wanted to avoid the unneeded complexity if this feature isn't needed but it isn't too difficult to implement.

**Comment by dnoe** [comment]
I think that's definitely possible, I'll check with @htuch about the proper way to do it.  I was under the impression your production environment had an alternate main.cc which is why I used that as the integration point.

**Comment by mattklein123** [comment]
We don't have an alternate main right now. We can make one, but IMO it would be easier to just support a define of some type that allows this feature to be turned off and on, and we can default to on for debug, maybe default to on for release, but have a way to disable if desired.

File: source/exe/signal_action.cc [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+  }
+  tracer.Log();
+
+  signal(sig, SIG_DFL);
+  raise(sig);
+}
+
+void SignalAction::InstallSigHandlers() {
+  stack_t stack;
+  stack.ss_sp = altstack_.get();
```
Comment (htuch) [inline source/exe/signal_action.cc]: Hang on a sec, how did this work?! :) Stacks grow down, so I think your stack was walking over the heap. Thanks for adding the guard page - when computing the initial SP, take the top address and subtract 8 bytes - that will give 64-bit alignment.

**Comment by dnoe** [comment]
(ASAN test fails because there is an invalid memory access - on purpose! - but the ASAN output when it dies is different from what my test expects.  I'll investigate how to address this tomorrow)

**Comment by htuch** [comment]
We could probably sneak the `main.cc` shim into this PR, it's just a simple file reorg and on point.

File: source/exe/signal_action.cc (hunk 6 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: No, I believe from the man page this is the correct way to interact with the implementation:

"       On most hardware architectures supported by Linux, stacks grow
       downward.  sigaltstack() automatically takes account of the direction
       of stack growth."

"       When a signal handler is invoked on the alternate stack, the kernel
       automatically aligns the address given in ss.ss_sp to a suitable
       address boundary for the underlying hardware architecture."

Comment (htuch) [inline source/exe/signal_action.cc]: Ah, great, that's reassuring :)

File: source/exe/signal_action.h (hunk 5 above)
Comment (dnoe) [inline source/exe/signal_action.h]: From the man page it is implementation defined which direction the stack grows within the memory block provided.  To fit within this it may be necessary to have a guard page on either side of the memory block provided to sigaltstack.

File: source/exe/signal_action.cc (hunk 1 above)
Comment (htuch) [inline source/exe/signal_action.cc]: Yeah. There's also `MAP_STACK | MAP_GROWSDOWN` that might be handy.

File: source/exe/signal_action.cc (hunk 2 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: I decided to skip this unneeded complexity for now, it isn't needed by any use case in Envoy today.  I can do it later if such a use case pops up.

File: source/exe/signal_action.cc [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+
+void SignalAction::SigHandler(int sig, siginfo_t* info, void* context) {
+  void* error_pc = 0;
+
+  const ucontext_t* ucontext = reinterpret_cast<const ucontext_t*>(context);
+  if (ucontext != nullptr) {
+#ifdef REG_RIP
+    // x86_64
+    error_pc = reinterpret_cast<void*>(ucontext->uc_mcontext.gregs[REG_RIP]);
+#elif defined(REG_EIP)
```
Comment (mattklein123) [inline source/exe/signal_action.cc]: nit: Can we just drop all of the elif clauses and have a single warning without the commented out code?

File: source/exe/signal_action.cc [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+  raise(sig);
+}
+
+void SignalAction::InstallSigHandlers() {
+  stack_t stack;
+  stack.ss_sp = altstack_ + GUARD_SIZE; // Guard page at one end ...
+  stack.ss_size = ALTSTACK_SIZE;        // ... guard page at the other
+  stack.ss_flags = 0;
+
+  if (sigaltstack(&stack, nullptr) < 0) {
```
Comment (mattklein123) [inline source/exe/signal_action.cc]: nit: Just drop the if statement here and just RELEASE_ASSERT the call directly, same for all cases below. You don't need any of the error output. Line # is enough.

File: source/exe/signal_action.cc [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+    RELEASE_ASSERT(false);
+  }
+  if (mprotect(altstack_ + GUARD_SIZE + ALTSTACK_SIZE, GUARD_SIZE, PROT_NONE) < 0) {
+    std::cerr << "Failed to protect signal stack memory: " << strerror(errno) << std::endl;
+    RELEASE_ASSERT(false);
+  }
+}
+
+void SignalAction::UnmapStackMemory() {
+  if (altstack_ != nullptr) {
```
Comment (mattklein123) [inline source/exe/signal_action.cc]: Can this ever happen with crashing?

File: source/exe/signal_action.h [hunk 10]
```diff
@@ -0,0 +1,110 @@
...
+ * scope, eg, in main(). This enables fatal signal handling for almost all code
+ * executed.
+ */
+class SignalAction {
+public:
+  SignalAction() : altstack_(nullptr) {
+    MapAndProtectStackMemory();
+    InstallSigHandlers();
+  }
+  SignalAction(const SignalAction&) = delete;
```
Comment (mattklein123) [inline source/exe/signal_action.h]: nit: You can derive from NonCopyable if you want.

File: source/exe/signal_action.h [hunk 11]
```diff
@@ -0,0 +1,110 @@
...
+  ~SignalAction() {
+    RemoveSigHandlers();
+    UnmapStackMemory();
+  }
+  /**
+   * Helpers for testing guarded stack memory
+   */
+  void DoGoodAccessForTest();
```
Comment (mattklein123) [inline source/exe/signal_action.h]: nit: style guide says methods start with lower case. Same for all methods here, and also in the backtrace file. Can you fix that also?

File: source/exe/signal_action.h [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+  void TryEvilAccessForTest(bool end);
+
+private:
+  /**
+   * Use this many bytes for the alternate signal handling stack.
+   *
+   * This should be a multiple of 4096.
```
Comment (mattklein123) [inline source/exe/signal_action.h]: nit: 4096 is arch dependent. It doesn't really matter but might want to put a note that is the case. Might want to at least hide behind constant.

File: source/server/backtrace.h [hunk 13]
```diff
@@ -83,6 +83,23 @@ class BackwardsTrace : Logger::Loggable<Logger::Id::backtrace> {
...
   /**
+   * Capture a stack trace from a particular address.
+   *
+   * This can be used to capture a useful stack trace from a fatal signal
+   * handler.
+   *
+   * @param address The stack trace will begin from this address.
+   */
+  void CaptureFrom(void* address) {
+#ifdef NDEBUG
```
Comment (mattklein123) [inline source/server/backtrace.h]: In practice, do we use any of the log in prod stuff anymore? Can we just kill it?

File: source/exe/signal_action.cc (hunk 7 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: I'd like to retain the examples as documentation, I believe they are correct but I have no easy way to test them at this time.  I'll lump it into one comment with an #else to keep it compact.

File: source/exe/signal_action.cc (hunk 9 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: Since we release assert if the mmap doesn't succeed, I believe the answer is no.  I can remove the check.  Inspecting the munmap man page it says "It is _not_ an error if the indicated range does not contain any mapped pages" and although addr must be page aligned 0x0 does actually obey this restriction so it seems to be a safe no-op anyway.

File: source/exe/signal_action.h (hunk 12 above)
Comment (dnoe) [inline source/exe/signal_action.h]: Programmatically it is hidden behind GUARD_SIZE - I'll update the comment.

File: source/server/backtrace.h (hunk 13 above)
Comment (dnoe) [inline source/server/backtrace.h]: Is it OK if backtraces are always logged at critical level? The point of the log_in_prod uglyness was to work around the fact that we don't actually emit logs below that level in optimized builds, and this feature should still be useful for investigating issues in optimized builds.  In practice with the signal handler either something has gone very wrong, or, a developer has manually added a statement to assist in debugging.  In both cases critical seems fine to me.

Comment (mattklein123) [inline source/server/backtrace.h]: Yup I would just use critical to simplify the code.

Comment (dnoe) [inline source/server/backtrace.h]: Awesome, I will add that into this PR.

File: tools/stack_decode.py [hunk 14]
```diff
@@ -58,18 +66,32 @@ def decode_stacktrace_log(input_source):
...
+
+# Output one stacktrace after passing it through addr2line with appropriate
+# options
+def output_stacktrace(thread_id, traceinfo):
+  output_lines = []
+  for address_list in traceinfo.obj_list:
+    piped_input = ""
+    obj_name = address_list.obj_file
+    # end of stack sentinel
+    if obj_name == "[0xffffffffffffffff]":
```
Comment (htuch) [inline tools/stack_decode.py]: Is this from Backward? This seems somewhat architecture specific, can you generalize?

File: test/exe/signals_test.cc [hunk 15]
```diff
@@ -0,0 +1,96 @@
...
+#endif
+
+// Memory violation signal tests are disabled under address sanitizer.  The
+// sanitizer does its own special signal handling and prints messages that are
+// not ours instead of what this test expects.  The signals special handled by ASAN
+// include SIGSEGV, SIGBUS, and SIGFPE.
+#ifndef ASANITIZED
+TEST(Signals, InvalidAddressDeathTest) {
+  SignalAction actions;
+  EXPECT_DEATH([]() -> void {
```
Comment (htuch) [inline test/exe/signals_test.cc]: You could make these tests much stronger by implementing the behavior we discussed, where you call the original signal handler after dumping the stack trace and installing a signal handler before the definitions of `actions`. That way you could verify that the stack trace dump signal handler didn't crash itself, and possibly that it ran if you set some global state.

Anyway, it's probably overkill for this kind of feature (you already have done a lot of test stuff), but just an FYI.

File: source/server/backtrace.h [hunk 16]
```diff
@@ -100,23 +117,32 @@ class BackwardsTrace : Logger::Loggable<Logger::Id::backtrace> {
...
+    auto obj_name = first_frame_trace.object_filename;
 
     LogAtLevel("Backtrace obj<{}> thr<{}> (use tools/stack_decode.py):", obj_name, thread_id);
 
     // Why start at 2? To hide the function call to backward that began the
     // trace.
     for (unsigned int i = 0; i < stack_trace_.size(); ++i) {
+      // Backtrace gets tagged by ASAN when we try the object name resolution for the last
+      // frame on stack, so skip the last one. It has no useful info anyway.
+      if (i + 1 != stack_trace_.size()) {
```
Comment (htuch) [inline source/server/backtrace.h]: Could you write `for (unsigned int i = 0; i < stack_trace.size() - 1; ++i) {` above and skip this conditional?

File: source/exe/signal_action.h (hunk 12 above)
Comment (htuch) [inline source/exe/signal_action.h]: mmap man page says you can use `sysconf(_SC_PAGE_SIZE)` to get this.

File: source/exe/signal_action.cc [hunk 17]
```diff
@@ -0,0 +1,119 @@
...
+    munmap(altstack_, MapSizeWithGuards());
+  }
+}
+
+void SignalAction::DoGoodAccessForTest() {
+  for (size_t i = 0; i < ALTSTACK_SIZE; ++i) {
+    *(altstack_ + GUARD_SIZE + i) = 42;
```
Comment (htuch) [inline source/exe/signal_action.cc]: These should be volatile pointers ideally and to prevent the compiler getting too smart.

File: source/exe/signal_action.cc (hunk 2 above)
Comment (htuch) [inline source/exe/signal_action.cc]: Sure. There's some value in it for tests, but I don't want to make this overkill.

File: source/server/backtrace.h (hunk 16 above)
Comment (dnoe) [inline source/server/backtrace.h]: I'm a little worried that this is arch specific, and Backwards won't always return this sentinel stack frame as the last item.  But, it should always be _safe_ to skip the last item, the risk is that we don't include some relevant stack frame.  I'll switch to stopping at size-1 which should guarantee no ASAN issues like I saw, at the possible risk of losing the bottom of stack which we probably don't care about anyway.

File: tools/stack_decode.py (hunk 14 above)
Comment (dnoe) [inline tools/stack_decode.py]: If I make the other change below to stop before the last item then this can be removed too.

File: source/exe/signal_action.h (hunk 11 above)
Comment (dnoe) [inline source/exe/signal_action.h]: I will fix this, looking at Google-styled code clearly warped by brain because I was carefully capitalizing the first letters.

File: test/exe/signals_test.cc (hunk 15 above)
Comment (dnoe) [inline test/exe/signals_test.cc]: That's an interesting idea.  It still isn't compatible with the ASAN issue, which seems to inhibit normal signal handling entirely, but it would make the test more robust.  I might implement the test as a "fun project" in a separate PR when I have some hacking time but if you're OK with the current state of the test I'm good with merging it as it stands.

File: source/exe/signal_action.cc (hunk 17 above)
Comment (dnoe) [inline source/exe/signal_action.cc]: I think even the smartest compile cannot assume that there are no side effects from writing into mmap'd memory even if it is technically anonymously mapped... but volatilized it just to be sure.

File: test/exe/signals_test.cc (hunk 15 above)
Comment (htuch) [inline test/exe/signals_test.cc]: Sure, whatever you reckon is best, I don't think we need this to merge.

File: source/exe/signal_action.cc (hunk 17 above)
Comment (htuch) [inline source/exe/signal_action.cc]: Thanks for fixing this. As an aside, it's my understanding that a compiler isn't required to keep track of the fact that a pointer is from mmapped memory, it's not possible in general (e.g. at module boundaries) since the C/C++ type system doesn't track this. As a result, it's allowed to treat any non-volatile pointer as a pointer to normal memory and subject to arbitrary optimization, without worrying about other observers and side-effects.

File: bazel/README.md [hunk 18]
```diff
@@ -116,6 +116,13 @@ bazel test -c dbg //test/server:backtrace_test
 You will need to use either a `dbg` build type or the `--define
 debug_symbols=yes` option to get symbol information in the binaries.
 
+By default main.cc will install signal handlers to print backtraces at the
+location where a fatal signal occurred.  The signal handler will re-raise the
+fatal signal with the default handler so a core file will still be dumped after
+the stack trace is logged.  To inhibit this behavior use
+`--define=signal_trace=disabled` on the Bazel command line. No signal handlers will
```
Comment (htuch) [inline bazel/README.md]: You might want to set this in the `tools/bazel.rc` for the ASAN runs. I'm not sure where ASAN installs its signal handlers (based on your experiences with the tests, it seems after this), but this might be safer in general to avoid conflict.

File: source/exe/BUILD [hunk 19]
```diff
@@ -52,6 +52,7 @@ envoy_cc_library(
     deps = [
         ":envoy_common_lib",
         ":hot_restart_lib",
+        ":sigaction_lib",
```
Comment (htuch) [inline source/exe/BUILD]: Can you use a `select` statement here and condition on `//bazel:disable_signal_trace` to avoid the link dependency on backward.hpp when we do the google import?

File: source/exe/signal_action.h [hunk 20]
```diff
@@ -0,0 +1,118 @@
...
+private:
+  /**
+   * Allocate this many bytes on each side of the area used for alt stack.
+   *
+   * Set to system page size.
+   *
+   * The memory will be protected from read and write.
+   */
+  const size_t guard_size_;
+  /**
```
Comment (htuch) [inline source/exe/signal_action.h]: Minor nit: we don't need Doxygen documentation for internal implementation variables, you can use regular C++ comments.

File: source/exe/signal_action.h [hunk 21]
```diff
@@ -0,0 +1,118 @@
...
+  void installSigHandlers();
+  /**
+   * Remove all signal handlers.
+   *
+   * Must be executed before the alt stack memory goes away.
+   *
+   * Signal handlers will be reset to the default, NOT back to any signal
+   * handler existing before InstallSigHandlers().
+   */
+  void removeSigHandlers() const;
```
Comment (htuch) [inline source/exe/signal_action.h]: It seems technically correct to use const here, since no member variables are modified, but it's somewhat strange to the reader as an annotation, as this method does mutate related global state (the process signal handlers). What do you think of the arguments for logical vs. physical constness of a method at https://isocpp.org/wiki/faq/const-correctness#logical-vs-physical-state? I'm thinking the signal handler table is in some sense being treated as part of the logical state of the object here.

File: source/exe/signal_action.h [hunk 22]
```diff
@@ -0,0 +1,118 @@
...
+ * executed.
+ */
+class SignalAction : NonCopyable {
+public:
+  SignalAction()
+      : guard_size_(sysconf(_SC_PAGE_SIZE)), altstack_size_(guard_size_ * 4), altstack_(nullptr) {
+    mapAndProtectStackMemory();
+    installSigHandlers();
+  }
+  SignalAction(const SignalAction&) = delete;
```
Comment (mattklein123) [inline source/exe/signal_action.h]: Nit: If you derive from NonCopyable you can delete this. It's redundant.

**Comment by mattklein123** [comment]
@dnoe FYI I put "Fixes https://github.com/lyft/envoy/issues/487" in the description of this PR. That will make it auto close that issue when this is merged.

File: source/exe/signal_action.h (hunk 22 above)
Comment (dnoe) [inline source/exe/signal_action.h]: D'oh, meant to include that in the change.  Thanks.

File: source/exe/signal_action.h (hunk 21 above)
Comment (dnoe) [inline source/exe/signal_action.h]: In theory the compiler could benefit from awareness that the method doesn't modify object state but in this particular instance I see no way that there is any practical impact.  And I agree that the method is not "logically" const, and there is benefit to not marking it as such.  Since any performance benefit from informing the compiler of immutable state is negligible in this case then I'm OK with removing the const.

File: source/exe/signal_action.h (hunk 20 above)
Comment (dnoe) [inline source/exe/signal_action.h]: Is there any reason NOT to use Doxygen formatted comments here? Doxygen can still produce useful documentation for private member vars depending on how it is configured to run.  I've found this information to be useful in past projects.

Comment (htuch) [inline source/exe/signal_action.h]: None other than inconsistency - if we don't have this documented as a convention across the code base in our style guide, then any Doxygen documentation on internal implementation details is a bit special snowflake. For example, unless we do have widespread agreement to use Doxygen for all documents, I plan on continuing to use // comments for internal comments.

File: bazel/README.md (hunk 18 above)
Comment (dnoe) [inline bazel/README.md]: This should be done now
