### PR TITLE
test: programatically derive temporary and generated paths for tests.

### LINKED ISSUE #605: Use standard API for temporary file paths in tests
Today, a number of tests use fixed paths in `/tmp` for their temporary file objects. Similar to #574, this presents problems in shared and/or sandboxed test environments, where tests may conflict with other runs or fail due to the lack of access to `/tmp`. We should use a standard API for accessing the temp path at various code sites where these paths are created (e.g. something like `TestEnvironment::tempPath()`) and also make the implementation of this respect variables like `TMPDIR`.

### PR DESCRIPTION
**Pull request by htuch**
Previously, there were some hardcoded /tmp paths for both generated artifacts and intermediate test
objects. This patch provides a TestEnvironment API to obtain these paths from the test runner, which
will assist with #415. In addition, the generation scripts and paths have been moved around a bit in
anticipation of #415.

Fixes #605.

### CODE REVIEW

File: test/common/filesystem/watcher_impl_test.cc [hunk 1]
```diff
@@ -13,36 +15,41 @@ TEST(WatcherImplTest, All) {
...
+               TestEnvironment::temporaryPath("envoy_test/watcher_new_link").c_str());
   RELEASE_ASSERT(0 == rc);
-  rename("/tmp/envoy_test/watcher_new_link", "/tmp/envoy_test/watcher_link");
+  rename(TestEnvironment::temporaryPath("envoy_test/watcher_new_link").c_str(),
+         TestEnvironment::temporaryPath("envoy_test/watcher_link").c_str());
   dispatcher.run(Event::Dispatcher::RunType::Block);
 }
 
-} // Filesystem
+} // namespace Filesystem
```
Comment (mattklein123) [inline test/common/filesystem/watcher_impl_test.cc]: This is a minor thing, but we haven't been doing this elsewhere in the code (prefix comment with "namespace"). We should probably do a cleanup if we want to unify on this style. I don't really care either way.

File: test/common/ssl/connection_impl_test.cc [hunk 2]
```diff
@@ -12,18 +12,27 @@
...
 using testing::_;
 using testing::Invoke;
 
 namespace Ssl {
 
-static void testUtil(std::string client_ctx_json, std::string server_ctx_json,
-                     std::string expected_digest, std::string expected_uri) {
+namespace {
+
+Json::ObjectPtr jsonLoad(const std::string& raw_json) {
```
Comment (mattklein123) [inline test/common/ssl/connection_impl_test.cc]: Should we put all the transforms like this in one place? Per our offline chat, if we eventually switch to using jinja, it will be easier to figure out what is going on?

Comment (mattklein123) [inline test/common/ssl/connection_impl_test.cc]: Nevermind, this is specific to this file.

File: test/test_common/environment.cc [hunk 3]
```diff
@@ -0,0 +1,24 @@
+#include "test/test_common/environment.h"
+
+#include "common/common/assert.h"
+
+namespace {
+
+std::string* getCheckedEnvVar(const std::string& var) {
```
Comment (mattklein123) [inline test/test_common/environment.cc]: unique_ptr

File: test/main.cc [hunk 4]
```diff
@@ -11,12 +11,16 @@
...
 #include "test/integration/integration.h"
 #endif
+#include "test/test_common/environment.h"
 
 int main(int argc, char** argv) {
   ::testing::InitGoogleMock(&argc, argv);
   Ssl::OpenSsl::initialize();
   Event::Libevent::Global::initialize();
 
+  ::testing::Test::RecordProperty("TemporaryDirectory", TestEnvironment::temporaryDirectory());
```
Comment (mattklein123) [inline test/main.cc]: I'm not familiar with this. Can you put a short comment on what these 2 lines actually do?

File: test/common/filesystem/watcher_impl_test.cc (hunk 1 above)
Comment (htuch) [inline test/common/filesystem/watcher_impl_test.cc]: Not sure how this crept in. The style guide says it should be prefixed but I don't care either. For anonymous namespaces we already do "// namespace" from a quick grep, which is useful as it indicates that there isn't a forgotten label there.

File: test/common/ssl/connection_impl_test.cc (hunk 2 above)
Comment (htuch) [inline test/common/ssl/connection_impl_test.cc]: Agreed - I moved it to TestEnvironment since the generated certs are not just for this test (e.g. they get used in the integration tests).

File: test/test_common/environment.cc (hunk 3 above)
Comment (htuch) [inline test/test_common/environment.cc]: The use of `new` in a function scoped `static` is one way to safely build a global/static non-POD object as per https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables. The `std::string` construction occurs on first use rather than non-deterministically. The object is never destructed, putting aside concerns over the non-deterministic destructor invocation ordering.

Thinking back to our previous discussion on this, I think I wasn't as concerned about non-POD globals due to the well behaved threading in Envoy. I still think the lack of destructor ordering is a problem (e.g. what if the `std::string` or `std::unique_ptr` is destroyed before some object with a ref to it?).

I recall the interplay with leak detection and this allocation style was a concern. Chatting @jamessynge, we came to the conclusion that the reason this doesn't trigger the leak detection is there is a reference from a live variable (the function scoped static) at program exit.

Comment (mattklein123) [inline test/test_common/environment.cc]: OK, as long as it doesn't fire the leak detector.
