### PR TITLE
Wrap static all_loggers in a function.

### LINKED ISSUE #1526: //test/tools/router_check/test:router_tool_test is flaky
```
$ bazel test //test/tools/router_check/test:router_tool_test --runs_per_test=1000

INFO: Analysed target //test/tools/router_check/test:router_tool_test (70 packages loaded).
INFO: Found 1 test target...
FAIL: //test/tools/router_check/test:router_tool_test (run 283 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_283_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 603 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_603_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 392 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_392_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 749 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_749_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 973 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_973_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 111 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_111_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 282 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_282_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 483 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_483_of_1000/test.log)
FAIL: //test/tools/router_check/test:router_tool_test (run 228 of 1000) (see /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_228_of_1000/test.log)

FAILED: //test/tools/router_check/test:router_tool_test (Summary)
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_283_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_603_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_392_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_749_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_973_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_111_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_282_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_483_of_1000/test.log
      /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_228_of_1000/test.log
Target //test/tools/router_check/test:router_tool_test up-to-date:
  bazel-bin/test/tools/router_check/test/router_tool_test
INFO: Elapsed time: 538.970s, Critical Path: 15.96s
INFO: Build completed, 1 test FAILED, 1009 total actions
//test/tools/router_check/test:router_tool_test                          FAILED in 9 out of 1000 in 5.3s
  Stats over 1000 runs: max = 5.3s, min = 0.6s, avg = 5.2s, dev = 0.3s
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_283_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_603_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_392_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_749_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_973_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_111_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_282_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_483_of_1000/test.log
  /home/zlizan/.cache/bazel/_bazel_zlizan/4a149353829fe3c044a2cdd221089b0b/execroot/envoy/bazel-out/local-dbg/testlogs/test/tools/router_check/test/router_tool_test/run_228_of_1000/test.log
```

The error log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
WARNING: Perftools heap leak checker is active -- Performance may suffer
Have memory regions w/o callers: might report false leaks
No leaks found for check "_main_" (but no 100% guarantee that there aren't any): found 3143 reachable heap objects of 1483553 bytes
```

### PR DESCRIPTION
**Pull request by hennna**
Wrap the static Logger variable all_loggers into a function to avoid the static initialization fiasco. 

This caused the router tool test to fail with a rate of ~1%.

Fixes #1526.

### CODE REVIEW

File: source/common/common/logger.cc [hunk 1]
```diff
@@ -14,14 +14,17 @@ namespace Logger {
...
-std::vector<Logger> Registry::all_loggers_ = {ALL_LOGGER_IDS(GENERATE_LOGGER)};
-
 Logger::Logger(const std::string& name) {
   logger_ = std::make_shared<spdlog::logger>(name, Registry::getSink());
   logger_->set_pattern("[%Y-%m-%d %T.%e][%t][%l][%n] %v");
   logger_->set_level(spdlog::level::trace);
 }
 
+std::vector<Logger>& Registry::allLoggers() {
+  static std::vector<Logger> all_loggers = {ALL_LOGGER_IDS(GENERATE_LOGGER)};
```
Comment (htuch) [inline source/common/common/logger.cc]: This should be `* all_loggers = new std::vector<logger>(initializers)`, otherwise you face the static destruction order fiasco.

File: source/common/common/logger.h [hunk 2]
```diff
@@ -100,12 +100,15 @@ class Registry {
   static void initialize(uint64_t log_level, Thread::BasicLockable& lock);
 
   /**
-   * @return const std::vector<Logger>& the installed loggers.
+   * @return const std::vector<Logger>& return a const reference to the installed loggers.
```
Comment (htuch) [inline source/common/common/logger.h]: Nit: I think the change is a bit redundant, since this information was there before.
