### PR TITLE
network: throw EnvoyException on address parse error

### LINKED ISSUE #952: Segfault with extra / on admin address
If you have 

```
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://127.0.0.1:8001/"
  }
```

(note the trailing `/` on the `address`) then Envoy will segfault. Deleting the trailing `/` cures the segfault.

Segfault is arguably a bit harsh as a misconfiguration diagnostic. ;)

### PR DESCRIPTION
**Pull request by hennna**
Previously when an IP address could not be parsed, a nullptr was returned. However, this causes a segfault for config files with error(s) in the address field(s). This PR changes the address parsing logic to throw an exception instead.

This PR also moves IP address parsing functions from Network::Address to Network::Utility.

Fixes #952

### CODE REVIEW

**Comment by hennna** [comment]
@ccaraman for review.

File: source/common/network/utility.cc [hunk 1]
```diff
@@ -129,6 +129,68 @@ uint32_t Utility::portFromTcpUrl(const std::string& url) {
...
+    sa6.sin6_family = AF_INET6;
+    sa6.sin6_port = 0;
+    return std::make_shared<Address::Ipv6Instance>(sa6);
+  }
+  throw EnvoyException(fmt::format("malformed IP address: {}", ip_address));
+}
+
+Address::InstanceConstSharedPtr
+Utility::parseInternetAddressAndPort(const std::string& ip_address) {
+  std::string error_msg(fmt::format("malformed IP address: {}", ip_address));
```
Comment (mattklein123) [inline source/common/network/utility.cc]: It would be best to not create this string when most times we will not need it. One solution is to move to a private helper function called ```throwOnMalformedIp(...)``` or something like that.

File: source/common/network/cidr_range.cc [hunk 2]
```diff
@@ -106,14 +106,14 @@ CidrRange CidrRange::create(InstanceConstSharedPtr address, int length) {
...
+  return create(Utility::parseInternetAddress(address), length);
 }
 
 // static
 CidrRange CidrRange::create(const std::string& range) {
   std::vector<std::string> parts = StringUtil::split(range, '/');
   if (parts.size() == 2) {
-    InstanceConstSharedPtr ptr = parseInternetAddress(parts[0]);
+    InstanceConstSharedPtr ptr = Utility::parseInternetAddress(parts[0]);
     if (ptr != nullptr && ptr->type() == Type::Ip) {
```
Comment (mattklein123) [inline source/common/network/cidr_range.cc]: null check here is no longer needed

File: source/common/network/utility.cc [hunk 3]
```diff
@@ -129,6 +129,71 @@ uint32_t Utility::portFromTcpUrl(const std::string& url) {
...
+    sa6.sin6_port = 0;
+    return std::make_shared<Address::Ipv6Instance>(sa6);
+  }
+  throw EnvoyException(fmt::format("malformed IP address: {}", ip_address));
+}
+
+Address::InstanceConstSharedPtr
+Utility::parseInternetAddressAndPort(const std::string& ip_address) {
+  if (ip_address.empty()) {
+    Utility::throwWithMalformedIp(ip_address);
```
Comment (mattklein123) [inline source/common/network/utility.cc]: nit: don't need to specify ```Utility::``` on these calls since already inside the class and static.

File: source/common/network/utility.cc [hunk 4]
```diff
@@ -129,6 +129,71 @@ uint32_t Utility::portFromTcpUrl(const std::string& url) {
...
+    sa4.sin_port = 0;
+    return std::make_shared<Address::Ipv4Instance>(&sa4);
+  }
+  sockaddr_in6 sa6;
+  if (inet_pton(AF_INET6, ip_address.c_str(), &sa6.sin6_addr) == 1) {
+    sa6.sin6_family = AF_INET6;
+    sa6.sin6_port = 0;
+    return std::make_shared<Address::Ipv6Instance>(sa6);
+  }
+  throw EnvoyException(fmt::format("malformed IP address: {}", ip_address));
```
Comment (htuch) [inline source/common/network/utility.cc]: `throwWithMalformedIp`?

File: source/common/network/utility.h [hunk 5]
```diff
@@ -78,6 +78,24 @@ class Utility {
...
+  * Parse an internet host address (IPv4 or IPv6) and create an Instance from it. Throw
+  * an exception if unable to parse the address. The address must not include a port number.
+  * @param ip_address string to be parsed as an internet address.
+  * @return pointer to the Instance, or nullptr if unable to parse the address.
+  */
+  static Address::InstanceConstSharedPtr parseInternetAddress(const std::string& ip_address);
+
+  /*
+  * Parse an internet host address (IPv4 or IPv6) AND port, and create an Instance from it.
+  * Throw an exception if unable to parse the address.
```
Comment (htuch) [inline source/common/network/utility.h]: You could also use an `@throws` Doxygen annotation, but this isn't common in the code base.
