### PR TITLE
Treating a bind failure as a connection failure rather than crashing Envoy

### LINKED ISSUE #1411: Support binding to a specific address when connecting to upstream servers
Like the title says. We should be able to specify an address for Envoy to bind to when connecting to upstream servers.

@htuch

### PR DESCRIPTION
**Pull request by alyssawilk**
Fixes #1411

### CODE REVIEW

File: test/common/network/connection_impl_test.cc [hunk 1]
```diff
@@ -502,6 +503,33 @@ TEST_P(ConnectionImplTest, BindTest) {
   disconnect(true);
 }
 
+TEST_P(ConnectionImplTest, BindFailureTest) {
+  std::string address_string = TestUtility::getIpv4Loopback();
```
Comment (htuch) [inline test/common/network/connection_impl_test.cc]: Tiny nit: prefer this initialization in the ` Network::Address::IpVersion::v6` clause below.

File: test/common/network/connection_impl_test.cc [hunk 2]
```diff
@@ -502,6 +503,33 @@ TEST_P(ConnectionImplTest, BindTest) {
...
+  if (GetParam() == Network::Address::IpVersion::v6) {
+    source_address_ = Network::Address::InstanceConstSharedPtr{
+        new Network::Address::Ipv4Instance(address_string, 0)};
+  } else {
+    address_string = "::1";
+    source_address_ = Network::Address::InstanceConstSharedPtr{
+        new Network::Address::Ipv6Instance(address_string, 0)};
+  }
+
+  if (dispatcher_.get() == nullptr) {
```
Comment (htuch) [inline test/common/network/connection_impl_test.cc]: Why do we need to condition this?

File: test/integration/integration_test.cc [hunk 3]
```diff
@@ -265,6 +270,36 @@ TEST_P(BindIntegrationTest, TestBind) {
        [&]() -> void { fake_upstream_connection_->waitForDisconnect(); }});
 }
 
+TEST_P(BindIntegrationTest, DISABLED_TestFailedBind) {
```
Comment (htuch) [inline test/integration/integration_test.cc]: Disabled?

File: test/integration/integration_test.cc [hunk 4]
```diff
@@ -220,7 +220,10 @@ TEST_P(IntegrationTest, WebSocketConnectionUpstreamDisconnect) {
 
 class BindIntegrationTest : public IntegrationTest {
 public:
-  void SetUp() override {
+  // Delay base class SetUp until initialize().
```
Comment (htuch) [inline test/integration/integration_test.cc]: Why is this needed?

File: source/common/network/connection_impl.cc [hunk 5]
```diff
@@ -94,6 +80,18 @@ ConnectionImpl::ConnectionImpl(Event::DispatcherImpl& dispatcher, int fd,
   file_event_ = dispatcher_.createFileEvent(
       fd_, [this](uint32_t events) -> void { onFileEvent(events); }, Event::FileTriggerType::Edge,
       Event::FileReadyType::Read | Event::FileReadyType::Write);
+
+  if (bind_to_address != nullptr) {
+    int rc = bind_to_address->bind(fd);
+    if (rc < 0) {
+      ENVOY_LOG_MISC(warn, "Bind failure. Failed to bind to {}: {}", bind_to_address->asString(),
```
Comment (mattklein123) [inline source/common/network/connection_impl.cc]: If something goes wrong here, this is going to mega spew the logs in a bad way. I'm guessing internally you have rate limiting on individual log messages. We don't have that in public code. I feel like we should have some kind of stat here for a bind error on connect? Perhaps this could be done like the buffer stats (which would be installed by the time you do the deferred close). At minimum we should probably have some kind of TODO here to think a bit more about how we would want to handle this operationally if we are not going to crash.

File: test/integration/integration_test.cc (hunk 4 above)
Comment (alyssawilk) [reply test/integration/integration_test.cc]: To allow the bind-fail test to override the address before set-up.

I'm fairly convinced that in the long run we should ditch SetUp for Initialize() (to allow common config manipulation) but I figured on doing that in one of the PRs for simplifying config set-up

File: source/common/network/connection_impl.cc (hunk 5 above)
Comment (htuch) [reply source/common/network/connection_impl.cc]: Maybe a counter and a `debug` level log would make sense.

File: test/integration/integration_test.cc (hunk 4 above)
Comment (htuch) [reply test/integration/integration_test.cc]: Sure. Maybe just add an explanation of why the delay then in the comment.

File: source/common/network/connection_impl.cc (hunk 5 above)
Comment (alyssawilk) [reply source/common/network/connection_impl.cc]: Man, if only we had some utility for logging important error messages infrequently.  Like a macro which logged with exponential back-off with a super cheap (if somewhat lossy) atomic counter to minimize CPU usage and cross thread contention.  And then eventually maybe even tie it into the stats system with the macro taking a custom label or line number for easy monitoring and trace-back of unexpected but not fatal occurrences...  That seems like it'd be super useful for debugging production issues for a large scale proxy.
I'll add porting this feature to my non-critical TODO list :-)

Comment (mattklein123) [reply source/common/network/connection_impl.cc]: FWIW, this is going to be a very infrequently used feature (you are probably the only one who will use it for now), so if you have this covered in some other way and you want to put in a TODO that's fine.

**Comment by alyssawilk** [comment]
Oh, I'm downgrading it to debug and adding a stat per harvey's suggestion.
I think it's a reasonable interim step, just cleaning up the tests now :-)

**Comment by alyssawilk** [comment]
Wasn't sure - it's a bind error on the socket to communicate with upstream
but upstream protocol errors is protocol errors *from* upstream and so I
thought there would be a case for confusion.

File: include/envoy/upstream/upstream.h [hunk 6]
```diff
@@ -217,6 +217,7 @@ class HostSet {
   COUNTER(upstream_flow_control_resumed_reading_total)                                             \
   COUNTER(upstream_flow_control_backed_up_total)                                                   \
   COUNTER(upstream_flow_control_drained_total)                                                     \
+  COUNTER(bind_errors)                                                                             \
```
[the remark this answers is not in the document]
Comment (dnoe) [reply include/envoy/upstream/upstream.h]: I agree upstream_bind_errors is confusing then. I think bind_errors is fine.

File: source/common/http/http1/conn_pool.cc [hunk 7]
```diff
@@ -268,6 +268,9 @@ ConnPoolImpl::ActiveClient::ActiveClient(ConnPoolImpl& parent)
   parent_.conn_connect_ms_ =
       parent_.host_->cluster().stats().upstream_cx_connect_ms_.allocateSpan();
   Upstream::Host::CreateConnectionData data = parent_.host_->createConnection(parent_.dispatcher_);
+  if (data.connection_->state() != Network::Connection::State::Open) {
```
Comment (mattklein123) [inline source/common/http/http1/conn_pool.cc]: IMO this approach is a bit fragile in that we don't really know that this is a bind error. Perhaps something else might change in the future? It also has the downside of not covering other cases such as tcp_proxy, redis, etc.

I see two options here:
1) Rename/extend `setBufferStats` (https://github.com/lyft/envoy/blob/master/include/envoy/network/connection.h#L147) to include other stats also. Then a call could pass in a bind failure stat if they want.
2) Make `createConnection()` take a struct with optional stats in it, which will force people to plumb things through as needed (though this would potentially require changes to more callsites).

Thoughts?

Comment (alyssawilk) [reply source/common/http/http1/conn_pool.cc]: We could avoid the first concern by just adding an ASSERT in the connection that if the connection isn't connected there is a bind failure, and adding a comment pointer to anyone changing the code.  Agree, the second, that this misses tcp_proxy, is more of a problem though.

setting buffer stats on creation looks super duper messy since for example in the case of the tcp proxy filter, the connection is created prior to the read callbacks which is where buffer stats are set  

I'd be inclined to go with renaming setBufferStats to be more general, and then somewhat unintuitively incrementing the bind error where we raise the error onFileEvent with a comment that we defer until the caller has a chance to set [buffer] stats.  If that doesn't sound too hacky to you I'll take a whack at that tomorrow

Comment (mattklein123) [reply source/common/http/http1/conn_pool.cc]: I think I'm fine with that unless you can think of a better option. I would rename to something like `setConnectionStats` or `setStats` or something.

Comment (alyssawilk) [reply source/common/http/http1/conn_pool.cc]: Done!

File: include/envoy/network/connection.h [hunk 8]
```diff
@@ -72,11 +72,12 @@ class Connection : public Event::DeferredDeletable, public FilterManager {
 public:
   enum class State { Open, Closing, Closed };
 
-  struct BufferStats {
+  struct ConnectionStats {
     Stats::Counter& read_total_;
     Stats::Gauge& read_current_;
     Stats::Counter& write_total_;
     Stats::Gauge& write_current_;
+    Stats::Counter* bind_errors_;
```
Comment (htuch) [inline include/envoy/network/connection.h]: Can you add a comment here on why this is a pointer rather than ref (upstream/downstream..)?

**Comment by alyssawilk** [comment]
Haha, *just* beat me to it :-P
