### PR TITLE
outlier: fix consecutive 5xx without interleaved success

### LINKED ISSUE #1491: Outlier detection: consecutive_5xx_ counter not reset after host ejection.
If a host in a cluster starts returning 5xx the host will only be ejected once.
If the host still returns 5xx after base_ejection_time_ms the host will not be ejected again until it has served a non 5xx response: https://github.com/lyft/envoy/blob/master/source/common/upstream/outlier_detection_impl.cc#L57

Should the consecutive_5xx_ counter be reset on ejection or set to (detector->config().consecutive5xx() -1)  (leaving the circuit breaker in an half-open state) ?

I believe this is what they are seeing in  https://github.com/istio/pilot/issues/1054

### PR DESCRIPTION
**Pull request by junr03**
Fixes #1491.

The DetectorHostSink has a consecutive_5xx_ counter that gets incremented every time a 5xx response gets charged to the sink, and reset every time a non-5xx does. Previously if a Sink reached the consecutive 5xx limit, and the host was charged with a consecutive 5xx ejection, the consecutive_5xx_ counter was not been reset. This meant that the Sink would not trigger another consecutive 5xx ejection until a non-5xx code was charged and the counter was reset, and then subsequently increased to the limit. This PR fixes the issue by resetting the counter after the host has been charged with an ejection (whether the ejection is enforced or not).

### CODE REVIEW

File: source/common/upstream/outlier_detection_impl.cc [hunk 1]
```diff
@@ -57,6 +57,12 @@ void DetectorHostSinkImpl::putHttpResponseCode(uint64_t response_code) {
     if (++consecutive_5xx_ ==
         detector->runtime().snapshot().getInteger("outlier_detection.consecutive_5xx",
                                                   detector->config().consecutive5xx())) {
+      // There are two outcomes here. The ejection will be enforced,
+      // or it won't. Either way the host won't trigger the check above if it keeps been
+      // charged with only 5xx ResponseCodes without an intervening non-5xx code. Therefore,
+      // the consecutive_5xx_ counter should be reset to allow the Sink to detect another bout
+      // of 5xx from this host.
+      consecutive_5xx_ = 0;
```
Comment (mattklein123) [inline source/common/upstream/outlier_detection_impl.cc]: It's a minor thing, but to avoid multiple threads thrashing I would do this in onConsecutive5xxWorker

File: source/common/upstream/outlier_detection_impl.cc [hunk 2]
```diff
@@ -248,6 +248,13 @@ void DetectorImpl::onConsecutive5xxWorker(HostSharedPtr host) {
     return;
   }
 
+  // There are two outcomes here. The ejection will be enforced,
```
Comment (mattklein123) [inline source/common/upstream/outlier_detection_impl.cc]: This comment does not fully make sense after the move.

Comment (mattklein123) [inline source/common/upstream/outlier_detection_impl.cc]: This comment still doesn't make sense unless I am confused. There is only 1 outcome here. The ejection has been enforced at this point, the host is being ejected, and we are resetting. Please also reflow the comment.

Also, I think the reset should happen after the ejection to avoid a small race condition and re-fire of the event.

**Comment by mattklein123** [comment]
@junr03 also please update PR description to final commit message. Thank you.

File: source/common/upstream/outlier_detection_impl.cc (hunk 2 above)
Comment (junr03) [inline source/common/upstream/outlier_detection_impl.cc]: the enforcement decision happens in the `ejectHost` function, so at this point the ejection can still be enforced or not.

If we do the reset after enforcing the ejection, we leave hosts whose ejection was not enforced in the problematic state.

Comment (mattklein123) [inline source/common/upstream/outlier_detection_impl.cc]: OK I see. I just meant move this code to after the ejectHost() call (so end of function). It will happen whether it gets ejected or not but in the case it is ejected there will be no race. Please reflow the comment and you have a small typo below "host keeps been".

Comment (junr03) [inline source/common/upstream/outlier_detection_impl.cc]: I see as well :). Updated the comment. I think this one flows a bit more clearly. Let me know.

File: source/common/upstream/outlier_detection_impl.cc [hunk 3]
```diff
@@ -250,6 +250,13 @@ void DetectorImpl::onConsecutive5xxWorker(HostSharedPtr host) {
 
   stats_.ejections_consecutive_5xx_.inc();
   ejectHost(host, EjectionType::Consecutive5xx);
+
+  // Reset the DetectorHostSink's consecutive_5xx_. This counter needs to be reset
+  // in order to allow the Sink to detect a bout of consecutive 5xx responses even
+  // if the sink is not charged with an interleaved non-5xx code.
+  // The reset is done here instead of the Sink's putHttpResponseCode call to prevent
```
Comment (mattklein123) [inline source/common/upstream/outlier_detection_impl.cc]: Still needs reflow with previous line.
