### PR TITLE
network/config: Add IPv6 DNS support

### LINKED ISSUE #978: DnsResolver v4/v6 selection
In adding v6 support to DnsResolver (https://github.com/lyft/envoy/blob/master/source/common/network/dns_impl.cc#L123), what would be the best way to handle v4/v6 address selection.

1. Default to v4/v6
2. Configurable option

For (1) something like try v6. If failed, try v4
For (2) something like a json parameter or CLI option that gets plumbed through to DnsResolver

### PR DESCRIPTION
**Pull request by hennna**
This PR adds IPv6 DNS support and adds a cluster config parameter "dns_lookup_ip_version" that specifies the DNS lookup IP address policy. The default policy if no parameter is specified is "v4_only".

Modifications were made to upstream_cluster and logical_dns_cluster to pass this parameter on when calling DnsResolver resolve. Modifications were made to dns_impl to add v6 support and also a fallback option when v4 dns lookup fails.

Fixes #978 .

### CODE REVIEW

**Comment by hennna** [comment]
@htuch  @jamessynge  for high level review and sanity check first

File: source/common/network/dns_impl.cc [hunk 1]
```diff
@@ -135,5 +160,13 @@ ActiveDnsQuery* DnsResolverImpl::resolve(const std::string& dns_name, ResolveCb
   }
 }
 
+void DnsResolverImpl::PendingResolution::getHostByName(int family) {
+  ares_gethostbyname(channel_, dns_name_.c_str(),
```
Comment (htuch) [inline source/common/network/dns_impl.cc]: As discussed IRL last week, `ares_gethostbyname()` can implement the IPv6-IPv4 fallback with `AF_UNSPEC` family set (but is badly documented). However, I think your current implementation gets us closer to where we want to be in #978, since it will allow for the return of both IPv6 and IPv4 addresses in a list in a future PR, where we can support the caller deciding upon fallback as a result of `connect()` failure. So, I reckon it's good to keep the explicit fallback in this PR.

File: docs/configuration/cluster_manager/cluster.rst [hunk 2]
```diff
@@ -144,6 +145,17 @@ dns_refresh_rate_ms
   the value defaults to 5000. For cluster types other than *strict_dns* and *logical_dns* this setting is
   ignored.
 
+.. _config_cluster_manager_cluster_dns_lookup_ip_version:
+
+dns_loopkup_ip_version
```
Comment (dnoe) [inline docs/configuration/cluster_manager/cluster.rst]: loopkup -> lookup

File: include/envoy/network/dns.h [hunk 3]
```diff
@@ -41,11 +41,14 @@ class DnsResolver {
...
    * Initiate an async DNS resolution.
    * @param dns_name supplies the DNS name to lookup.
+   * @param dns_lookup_ip_version the DNS IP version lookup policy.
    * @param callback supplies the callback to invoke when the resolution is complete.
    * @return if non-null, a handle that can be used to cancel the resolution.
    *         This is only valid until the invocation of callback or ~DnsResolver().
    */
-  virtual ActiveDnsQuery* resolve(const std::string& dns_name, ResolveCb callback) PURE;
+  virtual ActiveDnsQuery* resolve(const std::string& dns_name,
+                                  const std::string& dns_lookup_ip_version,
```
Comment (dnoe) [inline include/envoy/network/dns.h]: Instead of passing the dns_lookup_ip_version as a string, consider resolving it into an enum when you process the configuration and use that enum here. This will be cheaper than doing the string comparisons every time you resolve.

File: source/common/network/dns_impl.cc (hunk 1 above)
Comment (hennna) [inline source/common/network/dns_impl.cc]: It also seems that AF_UNSPEC has unexpected behavior (not a straightforward IPv6 lookup followed by a IPv4 lookup). Once that and returning multiple address types is added to the c-ares library, we can switch over to using AF_UNSPEC.

**Comment by hennna** [comment]
Updated. PTAL.

File: include/envoy/network/dns.h [hunk 4]
```diff
@@ -24,6 +24,8 @@ class ActiveDnsQuery {
   virtual void cancel() PURE;
 };
 
+enum class DnsLookupFamily { v4_only, v6_only, fallback };
```
Comment (htuch) [inline include/envoy/network/dns.h]: Nit: CAPS for enums for consistency:

File: include/envoy/network/dns.h [hunk 5]
```diff
@@ -41,11 +43,14 @@ class DnsResolver {
...
    * Initiate an async DNS resolution.
    * @param dns_name supplies the DNS name to lookup.
+   * @param dns_lookup_family the DNS IP version lookup policy.
    * @param callback supplies the callback to invoke when the resolution is complete.
    * @return if non-null, a handle that can be used to cancel the resolution.
    *         This is only valid until the invocation of callback or ~DnsResolver().
    */
-  virtual ActiveDnsQuery* resolve(const std::string& dns_name, ResolveCb callback) PURE;
+  virtual ActiveDnsQuery* resolve(const std::string& dns_name,
+                                  const DnsLookupFamily& dns_lookup_family,
```
Comment (htuch) [inline include/envoy/network/dns.h]: I would just pass this by value, it might even be more efficient to do so (it's just a small integer).

File: source/common/json/config_schemas.cc [hunk 6]
```diff
@@ -1210,6 +1210,10 @@ const std::string Json::Schema::CLUSTER_SCHEMA(R"EOF(
         "minimum" : 0,
         "exclusiveMinimum" : true
       },
+      "dns_lookup_family" : {
+        "type" : "string",
+        "enum" : ["v4_only", "v6_only", "auto"]
```
Comment (htuch) [inline source/common/json/config_schemas.cc]: Docs say `fallback`, but it's `auto` here.

File: source/common/network/dns_impl.cc [hunk 7]
```diff
@@ -52,25 +52,41 @@ void DnsResolverImpl::PendingResolution::onAresHostCallback(int status, hostent*
...
+      }
+    } else if (hostent->h_addrtype == AF_INET6) {
+      for (int i = 0; hostent->h_addr_list[i] != nullptr; ++i) {
+        ASSERT(hostent->h_length == sizeof(in6_addr));
+        sockaddr_in6 address;
+        memset(&address, 0, sizeof(address));
+        address.sin6_family = AF_INET6;
+        address.sin6_port = 0;
+        address.sin6_addr = *reinterpret_cast<in6_addr*>(hostent->h_addr_list[i]);
+        address_list.emplace_back(new Address::Ipv6Instance(address));
```
Comment (htuch) [inline source/common/network/dns_impl.cc]: Unrelated to your review, but it seems weird that the `sockeadd[_in6]` constructors for `Ipv4Instance` and `Ipv6Instance` differ in whether they take a pointer or reference.

File: source/common/network/dns_impl.cc [hunk 8]
```diff
@@ -52,25 +52,41 @@ void DnsResolverImpl::PendingResolution::onAresHostCallback(int status, hostent*
...
+      }
     }
+  } else if (fallback_if_failed) {
+    fallback_if_failed = false;
+    getHostByName(AF_INET);
   }
-  if (!cancelled_) {
+  if (!cancelled_ && completed_) {
```
Comment (htuch) [inline source/common/network/dns_impl.cc]: Nit: You can move both `if` clauses under a `if (completed_) {`.

File: source/common/network/dns_impl.cc [hunk 9]
```diff
@@ -115,17 +131,26 @@ void DnsResolverImpl::onAresSocketStateChange(int fd, int read, int write) {
                           (write ? Event::FileReadyType::Write : 0));
 }
 
-ActiveDnsQuery* DnsResolverImpl::resolve(const std::string& dns_name, ResolveCb callback) {
+ActiveDnsQuery* DnsResolverImpl::resolve(const std::string& dns_name,
+                                         const DnsLookupFamily& dns_lookup_family,
+                                         ResolveCb callback) {
   std::unique_ptr<PendingResolution> pending_resolution(new PendingResolution());
   pending_resolution->callback_ = callback;
+  pending_resolution->channel_ = channel_;
```
Comment (htuch) [inline source/common/network/dns_impl.cc]: As a cleanup to my earlier mess, you could make all of these constructor args and initialize them in the constructor's member initializor list, allowing them to be made `const`.

File: source/common/network/dns_impl.cc [hunk 10]
```diff
@@ -52,25 +52,41 @@ void DnsResolverImpl::PendingResolution::onAresHostCallback(int status, hostent*
...
+        memset(&address, 0, sizeof(address));
+        address.sin6_family = AF_INET6;
+        address.sin6_port = 0;
+        address.sin6_addr = *reinterpret_cast<in6_addr*>(hostent->h_addr_list[i]);
+        address_list.emplace_back(new Address::Ipv6Instance(address));
+      }
     }
+  } else if (fallback_if_failed) {
+    fallback_if_failed = false;
+    getHostByName(AF_INET);
```
Comment (htuch) [inline source/common/network/dns_impl.cc]: I think there's a dangerous corner case here. If the first `getHostByName()` defers to asynch completion but then the fallback `getHostByName()` succeeds immediately (synchronously), it will invoke the callback, which will `delete this;`. This will then return to the caller method belonging to a now deleted object.

File: source/common/json/config_schemas.cc (hunk 6 above)
Comment (RomanDzhabarov) [inline source/common/json/config_schemas.cc]: I actually, like 'auto' for consistency with other settings (just fix the doc)

File: source/common/network/dns_impl.cc [hunk 11]
```diff
@@ -135,5 +160,13 @@ ActiveDnsQuery* DnsResolverImpl::resolve(const std::string& dns_name, ResolveCb
   }
 }
 
+void DnsResolverImpl::PendingResolution::getHostByName(int family) {
+  ares_gethostbyname(channel_, dns_name_.c_str(),
+                     family, [](void* arg, int status, int timeouts, hostent* hostent) {
+                       static_cast<PendingResolution*>(arg)->onAresHostCallback(status, hostent);
+                       UNREFERENCED_PARAMETER(timeouts);
```
Comment (RomanDzhabarov) [inline source/common/network/dns_impl.cc]: i think you should be able to (void *arg, int status, int, hostent* hostent) and remove UNREFERENCED_PARAMETER.

File: source/common/network/dns_impl.h [hunk 12]
```diff
@@ -53,6 +54,13 @@ class DnsResolverImpl : public DnsResolver {
     bool completed_ = false;
     // Was the query cancelled via cancel()?
     bool cancelled_ = false;
+    // If dns_lookup_family is "fallback", fallback to v4 address if v6
+    // resolution failed.
+    bool fallback_if_failed = false;
+    ares_channel channel_;
+    std::string dns_name_;
+
+    void getHostByName(int family);
```
Comment (RomanDzhabarov) [inline source/common/network/dns_impl.h]: nit: put this right after void onAresHostCallback(int status, hostent* hostent);

File: source/common/upstream/logical_dns_cluster.cc [hunk 13]
```diff
@@ -20,12 +20,20 @@ LogicalDnsCluster::LogicalDnsCluster(const Json::Object& config, Runtime::Loader
...
   }
 
+  // Resolve string to enum.
+  std::string dns_lookup_family = config.getString("dns_lookup_family", "v4_only");
+  if (dns_lookup_family == "v6_only") {
+    dns_lookup_family_ = Network::DnsLookupFamily::v6_only;
+  } else if (dns_lookup_family == "fallback") {
+    dns_lookup_family_ = Network::DnsLookupFamily::fallback;
+  } else {
+    dns_lookup_family_ = Network::DnsLookupFamily::v4_only;
```
Comment (RomanDzhabarov) [inline source/common/upstream/logical_dns_cluster.cc]: for being on a defensive side can you assert here that dns_lookup_family is equal to "v4_only".

File: source/common/upstream/logical_dns_cluster.cc [hunk 14]
```diff
@@ -20,12 +20,20 @@ LogicalDnsCluster::LogicalDnsCluster(const Json::Object& config, Runtime::Loader
           std::chrono::milliseconds(config.getInteger("dns_refresh_rate_ms", 5000))),
       tls_(tls), tls_slot_(tls.allocateSlot()), initialized_(false),
       resolve_timer_(dispatcher.createTimer([this]() -> void { startResolve(); })) {
-
   std::vector<Json::ObjectSharedPtr> hosts_json = config.getObjectArray("hosts");
   if (hosts_json.size() != 1) {
     throw EnvoyException("logical_dns clusters must have a single host");
   }
 
+  // Resolve string to enum.
```
Comment (RomanDzhabarov) [inline source/common/upstream/logical_dns_cluster.cc]: up to you, but the comment does not add value, it's pretty straightforward what's happening here

File: source/common/upstream/logical_dns_cluster.cc [hunk 15]
```diff
@@ -51,18 +59,26 @@ void LogicalDnsCluster::startResolve() {
...
         if (!address_list.empty()) {
-          // TODO(mattklein123): IPv6 support as well as moving port handling into the DNS
-          // interface.
-          Network::Address::InstanceConstSharedPtr new_address(
-              new Network::Address::Ipv4Instance(address_list.front()->ip()->addressAsString(),
-                                                 Network::Utility::portFromTcpUrl(dns_url_)));
+          // TODO(mattklein123): Move port handling into the DNS interface.
+          Network::Address::IpVersion version = address_list.front()->ip()->version();
+          Network::Address::InstanceConstSharedPtr new_address;
+          if (version == Network::Address::IpVersion::v4) {
```
Comment (RomanDzhabarov) [inline source/common/upstream/logical_dns_cluster.cc]: can you do switch here, so we make sure that compiler will complain in case enum values changes (with low probability though :))

File: source/common/upstream/logical_dns_cluster.cc [hunk 16]
```diff
@@ -77,8 +93,13 @@ void LogicalDnsCluster::startResolve() {
             // to show the friendly DNS name in that output, but currently there is no way to
             // express a DNS name inside of an Address::Instance. For now this is OK but we might
             // want to do better again later.
-            logical_host_.reset(new LogicalHost(
-                info_, hostname_, Network::Utility::resolveUrl("tcp://0.0.0.0:0"), *this));
+            if (version == Network::Address::IpVersion::v4) {
```
Comment (RomanDzhabarov) [inline source/common/upstream/logical_dns_cluster.cc]: ditto

File: source/common/json/config_schemas.cc (hunk 6 above)
Comment (hennna) [inline source/common/json/config_schemas.cc]: The problem with auto is that it's a keyword and can't be used when making the string->enum conversion.

Comment (RomanDzhabarov) [inline source/common/json/config_schemas.cc]: bummer :(

Comment (hennna) [inline source/common/json/config_schemas.cc]: Actually AUTO might be okay

File: include/envoy/network/dns.h (hunk 4 above)
Comment (hennna) [inline include/envoy/network/dns.h]: It seems there are enums with all caps (https://github.com/lyft/envoy/blob/998b8119ed57269e77d0a03b1b92e7a98c5d30d1/source/server/config/network/http_connection_manager.h#L114) but also many cases of not all caps (https://github.com/lyft/envoy/blob/998b8119ed57269e77d0a03b1b92e7a98c5d30d1/source/server/config/network/http_connection_manager.h#L24) Which is the convention?

Comment (htuch) [inline include/envoy/network/dns.h]: This came up in another PR recently: https://github.com/lyft/envoy/pull/989/files/431c909dcd7d70686cc9986c9ef019bef8942ae2#r117533920

I think we are going with all-caps. Feel free to create a https://github.com/lyft/envoy/blob/master/STYLE.md to codify.

File: source/common/upstream/logical_dns_cluster.cc [hunk 17]
```diff
@@ -51,18 +59,29 @@ void LogicalDnsCluster::startResolve() {
...
         if (!address_list.empty()) {
-          // TODO(mattklein123): IPv6 support as well as moving port handling into the DNS
-          // interface.
-          Network::Address::InstanceConstSharedPtr new_address(
-              new Network::Address::Ipv4Instance(address_list.front()->ip()->addressAsString(),
-                                                 Network::Utility::portFromTcpUrl(dns_url_)));
+          // TODO(mattklein123): Move port handling into the DNS interface.
+          Network::Address::IpVersion version = address_list.front()->ip()->version();
+          Network::Address::InstanceConstSharedPtr new_address;
+          switch (version) {
```
Comment (htuch) [inline source/common/upstream/logical_dns_cluster.cc]: This stuff can probably be factored out. You can add to `Network::Address::Instance` a `withPort(int port)` method that returns a new address with the port replaced as done here.

File: source/common/upstream/upstream_impl.cc [hunk 18]
```diff
@@ -424,11 +434,22 @@ void StrictDnsClusterImpl::ResolveTarget::startResolve() {
...
+                Network::Address::InstanceConstSharedPtr{
+                    new Network::Address::Ipv4Instance(address->ip()->addressAsString(), port_)},
+                false, 1, ""));
+            break;
+          case Network::Address::IpVersion::v6:
+            new_hosts.emplace_back(new HostImpl(
+                parent_.info_, dns_address_,
+                Network::Address::InstanceConstSharedPtr{
+                    new Network::Address::Ipv6Instance(address->ip()->addressAsString(), port_)},
+                false, 1, ""));
```
Comment (htuch) [inline source/common/upstream/upstream_impl.cc]: As mentioned above.

File: test/common/upstream/logical_dns_cluster_test.cc [hunk 19]
```diff
@@ -88,13 +88,67 @@ TEST_F(LogicalDnsClusterTest, ImmediateResolve) {
...
+  )EOF";
+
+  EXPECT_CALL(initialized_, ready());
+  EXPECT_CALL(dns_resolver_, resolve("foo.bar.com", Network::DnsLookupFamily::AUTO, _))
+      .WillOnce(Invoke([&](const std::string&, const Network::DnsLookupFamily&,
+                           Network::DnsResolver::ResolveCb cb) -> Network::ActiveDnsQuery* {
+        EXPECT_CALL(*resolve_timer_, enableTimer(_));
+        cb(TestUtility::makeDnsResponse({"::1"}));
+        return nullptr;
+      }));
```
Comment (htuch) [inline test/common/upstream/logical_dns_cluster_test.cc]: There might be an argument for using `TEST_P` here, but I'm not sure it's worth the effort and it's probably more readable the way you've done it.

File: test/common/upstream/upstream_impl_test.cc [hunk 20]
```diff
@@ -80,12 +80,80 @@ TEST(StrictDnsClusterImplTest, ImmediateResolve) {
...
+                           Network::DnsResolver::ResolveCb cb) -> Network::ActiveDnsQuery* {
+        cb(TestUtility::makeDnsResponse({"::1", "::2"}));
+        return nullptr;
+      }));
+  Json::ObjectSharedPtr loader = Json::Factory::loadFromString(json);
+  StrictDnsClusterImpl cluster(*loader, runtime, stats, ssl_context_manager, dns_resolver,
+                               dispatcher);
+  cluster.setInitializedCb([&]() -> void { initialized.ready(); });
+  EXPECT_EQ(2UL, cluster.hosts().size());
+  EXPECT_EQ(2UL, cluster.healthyHosts().size());
```
Comment (htuch) [inline test/common/upstream/upstream_impl_test.cc]: Actually, I think for these bigger examples, `TEST_P` would make more sense. You can make the parameter a `std::tuple` of string for the `dns_lookup_family`, DNS family and the DNS response list.

File: test/common/upstream/upstream_impl_test.cc [hunk 21]
```diff
@@ -80,12 +80,80 @@ TEST(StrictDnsClusterImplTest, ImmediateResolve) {
...
+}
+
+TEST(StrictDnsClusterImplTest, ImmediateResolveV6Only) {
```
Comment (htuch) [inline test/common/upstream/upstream_impl_test.cc]: Is there also `LogicalDnsClusterImplTest`?

Comment (hennna) [inline test/common/upstream/upstream_impl_test.cc]: Yes, there's a logical_dns_cluster_test.cc

**Comment by RomanDzhabarov** [comment]
@htuch let me make the last pass also

File: source/common/network/utility.cc [hunk 22]
```diff
@@ -299,6 +299,17 @@ Address::InstanceConstSharedPtr Utility::getIpv6AnyAddress() {
   return any;
 }
 
+Address::InstanceConstSharedPtr Utility::getAddressUpdatePort(const Address::Instance& address,
```
Comment (htuch) [inline source/common/network/utility.cc]: Prefer `addressWithPort`.

File: STYLE.md [hunk 23]
```diff
@@ -17,6 +17,7 @@
   includes both const and non-const references.
 * Function names using camel case starting with a lower case letter (e.g., "doFoo()").
 * Struct/Class member variables have a '\_' postfix (e.g., "int foo\_;").
+* Enum values using all CAPS (e.g., "EXTERNAL_ONLY").
```
Comment (RomanDzhabarov) [inline STYLE.md]: hm, I'm not sure about this.
grep -ir 'enum class' gives the majority of the enum values in PascalCase.

Any particular reason we want to stick to the all CAPS?

**Comment by htuch** [comment]
I think mattklein123@ advocated for this in
https://github.com/lyft/envoy/pull/989#discussion_r117533920. I don't have
a strong opinion as long as we are consistent with this and document.

File: STYLE.md (hunk 23 above)
Comment (hennna) [inline STYLE.md]: It actually looks like #989 was referring to static const values. Should I hard code PascalCase in the style guide?

Comment (RomanDzhabarov) [inline STYLE.md]: yeah, I'd do Pascal and create an issue to clean up all of the enum values which do not conform this rule (Those are mostly have HTTPX form)

@henna @htuch what would you say?

Comment (hennna) [inline STYLE.md]: SGTM

File: source/common/network/dns_impl.h [hunk 24]
```diff
@@ -29,30 +29,46 @@ class DnsResolverImpl : public DnsResolver {
...
+        : callback_(callback), channel_(channel), dns_name_(dns_name) {}
+
     void cancel() override {
       // c-ares only supports channel-wide cancellation, so we just allow the
       // network events to continue but don't invoke the callback on completion.
       cancelled_ = true;
     }
 
-    // c-ares ares_gethostbyname() query callback.
+    /* c-ares ares_gethostbyname() query callback.
```
Comment (ccaraman) [inline source/common/network/dns_impl.h]: nit:  add /** before this line

File: source/common/network/dns_impl.h [hunk 25]
```diff
@@ -29,30 +29,46 @@ class DnsResolverImpl : public DnsResolver {
...
+     * @param status return status of call to ares_gethostbyname.
+     * @param hostent structure that stores information about a given host.
+     */
     void onAresHostCallback(int status, hostent* hostent);
+    /* wrapper function of call to ares_gethostbyname.
```
Comment (ccaraman) [inline source/common/network/dns_impl.h]: nit: add /** before this line

**Comment by RomanDzhabarov** [comment]
+1
