### PR TITLE
Fix for upstream_request_ / request_encoder_ lifetime issues

### LINKED ISSUE #1443: Router watermark crash
```
Backtrace:
#0  Envoy::Router::Filter::onBelowWriteBufferLowWatermark (this=0x2218b190) at external/envoy/source/common/router/router.cc:308
#0  Envoy::Router::Filter::onBelowWriteBufferLowWatermark (this=0x2218b190) at external/envoy/source/common/router/router.cc:308
#1  0x00000000005167bd in callLowWatermarkCallbacks (this=<optimized out>) at external/envoy/source/common/http/conn_manager_impl.cc:912
#2  Envoy::Http::ConnectionManagerImpl::onBelowWriteBufferLowWatermark (this=0x842f800) at bazel-out/local-opt/bin/external/envoy/source/common/http/_virtual_includes/conn_manager_lib/common/http/conn_manager_impl.h:299
#3  0x00000000005011aa in onLowWatermark (this=0x123d2880) at external/envoy/source/common/network/connection_impl.cc:311
#4  operator() (__closure=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:64
#5  std::_Function_handler<void(), Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::DispatcherImpl&, int, Envoy::Network::Address::InstanceConstSharedPtr, Envoy::Network::Address::InstanceConstSharedPtr, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5/functional:1871
#6  0x0000000000501030 in Envoy::Ssl::ConnectionImpl::doWriteToSocket (this=this@entry=0x123d2880) at external/envoy/source/common/ssl/connection_impl.cc:213
#7  0x00000000005010bf in Envoy::Ssl::ConnectionImpl::doWriteToSocket (this=0x123d2880) at external/envoy/source/common/ssl/connection_impl.cc:162
#8  0x0000000000501cab in Envoy::Network::ConnectionImpl::onWriteReady (this=0x123d2880) at external/envoy/source/common/network/connection_impl.cc:459
#9  0x00000000004944f8 in operator() (__args#0=2, this=<optimized out>) at /usr/include/c++/5/functional:2267
#10 operator() (__closure=0x0, arg=<optimized out>, what=<optimized out>) at external/envoy/source/common/event/file_event_impl.cc:60
#11 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) () at external/envoy/source/common/event/file_event_impl.cc:61
#12 0x00000000006116b2 in event_persist_closure (ev=<optimized out>, base=0x1302840) at event.c:1580
#13 event_process_active_single_queue (base=base@entry=0x1302840, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at event.c:1639
#14 0x0000000000611e0f in event_process_active (base=0x1302840) at event.c:1738
#15 event_base_loop (base=0x1302840, flags=0) at event.c:1961
#16 0x0000000000491039 in Envoy::Server::WorkerImpl::threadRoutine (this=0x16daae0, guard_dog=...) at external/envoy/source/server/worker_impl.cc:110
#17 0x000000000061b11e in Envoy::Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) () at /usr/include/c++/5/functional:2267
#18 0x00007f393b17d184 in start_thread (arg=0x7f3939b48700) at pthread_create.c:312
#19 0x00007f393aea9ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

### LINKED ISSUE #1447: Upstream connection watermark crash
```
Backtrace:
#0  runHighWatermarkCallbacks (this=<optimized out>) at bazel-out/local-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:19
#0  runHighWatermarkCallbacks (this=<optimized out>) at bazel-out/local-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:19
#1  onUnderlyingConnectionAboveWriteBufferHighWatermark (this=0x38a1ff0) at bazel-out/local-opt/bin/external/envoy/source/common/http/http2/_virtual_includes/codec_lib/common/http/http2/codec_impl.h:269
#2  Envoy::Http::CodecClient::onAboveWriteBufferHighWatermark (this=<optimized out>) at bazel-out/local-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_client_lib/common/http/codec_client.h:188
#3  0x00000000004ffe6a in onHighWatermark (this=0x39b5c80) at external/envoy/source/common/network/connection_impl.cc:316
#4  operator() (__closure=<optimized out>) at external/envoy/source/common/network/connection_impl.cc:64
#5  std::_Function_handler<void(), Envoy::Network::ConnectionImpl::ConnectionImpl(Envoy::Event::DispatcherImpl&, int, Envoy::Network::Address::InstanceConstSharedPtr, Envoy::Network::Address::InstanceConstSharedPtr)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/5/functional:1871
#6  0x0000000000500164 in Envoy::Network::ConnectionImpl::write (this=0x39b5c80, data=...) at external/envoy/source/common/network/connection_impl.cc:272
#7  0x00000000005fa0fc in Envoy::Http::Http2::ConnectionImpl::onSend (this=0x38a1ff8, data=<optimized out>, length=13) at external/envoy/source/common/http/http2/codec_impl.cc:509
#8  0x000000000060231c in nghttp2_session_send (session=0x3978a00) at nghttp2_session.c:3210
#9  0x00000000005fb48f in Envoy::Http::Http2::ConnectionImpl::sendPendingFrames (this=this@entry=0x38a1ff8) at external/envoy/source/common/http/http2/codec_impl.cc:566
#10 0x00000000005fb507 in Envoy::Http::Http2::ConnectionImpl::sendPendingFrames (this=0x38a1ff8) at external/envoy/source/common/http/http2/codec_impl.cc:591
#11 0x0000000000675eea in Envoy::Router::Filter::onDestroy (this=0xdb8dbd0) at external/envoy/source/common/router/router.cc:362
#12 0x00000000005ea5ae in Envoy::Http::ConnectionManagerImpl::doDeferredStreamDestroy (this=0x75d4260, stream=...) at external/envoy/source/common/http/conn_manager_impl.cc:147
#13 0x00000000005fa292 in runResetCallbacks (reason=Envoy::Http::RemoteReset, this=0xebaf688) at bazel-out/local-opt/bin/external/envoy/source/common/http/_virtual_includes/codec_helper_lib/common/http/codec_helper.h:30
#14 Envoy::Http::Http2::ConnectionImpl::onStreamClose (this=0x4432ca8, stream_id=19813, error_code=<optimized out>) at external/envoy/source/common/http/http2/codec_impl.cc:522
#15 0x00000000005fe6ed in nghttp2_session_close_stream (session=session@entry=0x58e2800, stream_id=19813, error_code=0) at nghttp2_session.c:1169
#16 0x00000000005ffd94 in nghttp2_session_on_rst_stream_received (session=0x58e2800, frame=0x58e2998) at nghttp2_session.c:4126
#17 0x0000000000603a67 in session_process_rst_stream_frame (session=0x58e2800) at nghttp2_session.c:4140
#18 nghttp2_session_mem_recv (session=0x58e2800, in=0x474ad13 "", inlen=4048) at nghttp2_session.c:5862
#19 0x00000000005fb9bf in Envoy::Http::Http2::ConnectionImpl::dispatch (this=0x4432ca8, data=...) at external/envoy/source/common/http/http2/codec_impl.cc:300
#20 0x00000000005ea3a8 in Envoy::Http::ConnectionManagerImpl::onData (this=0x75d4260, data=...) at external/envoy/source/common/http/conn_manager_impl.cc:191
#21 0x0000000000502739 in Envoy::Network::FilterManagerImpl::onContinueReading (this=this@entry=0x7da0dc8, filter=filter@entry=0x0) at external/envoy/source/common/network/filter_manager_impl.cc:61
#22 0x00000000005027ac in Envoy::Network::FilterManagerImpl::onRead (this=this@entry=0x7da0dc8) at external/envoy/source/common/network/filter_manager_impl.cc:71
#23 0x0000000000500859 in onRead (read_buffer_size=82595, this=0x7da0dc0) at external/envoy/source/common/network/connection_impl.cc:195
#24 Envoy::Network::ConnectionImpl::onReadReady (this=0x7da0dc0) at external/envoy/source/common/network/connection_impl.cc:393
#25 0x00000000005009c3 in Envoy::Network::ConnectionImpl::onFileEvent (this=0x7da0dc0, events=3) at external/envoy/source/common/network/connection_impl.cc:341
#26 0x0000000000497788 in operator() (__args#0=3, this=<optimized out>) at /usr/include/c++/5/functional:2267
#27 operator() (__closure=0x0, arg=<optimized out>, what=<optimized out>) at external/envoy/source/common/event/file_event_impl.cc:60
#28 Envoy::Event::FileEventImpl::<lambda(int, short int, void*)>::_FUN(int, short, void *) () at external/envoy/source/common/event/file_event_impl.cc:61
#29 0x00000000006c88a2 in event_persist_closure (ev=<optimized out>, base=0x323e580) at event.c:1580
#30 event_process_active_single_queue (base=base@entry=0x323e580, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0, activeq=<optimized out>) at event.c:1639
#31 0x00000000006c8fff in event_process_active (base=0x323e580) at event.c:1738
#32 event_base_loop (base=0x323e580, flags=0) at event.c:1961
#33 0x0000000000494639 in Envoy::Server::WorkerImpl::threadRoutine (this=0x340a120, guard_dog=...) at external/envoy/source/server/worker_impl.cc:110
#34 0x00000000006d230e in Envoy::Thread::Thread::Thread(std::function<void ()>)::{lambda(void*)#1}::_FUN(void*) () at /usr/include/c++/5/functional:2267
#35 0x00007fb96cac0184 in start_thread (arg=0x7fb96bc8c700) at pthread_create.c:312
#36 0x00007fb96c7ecffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

### PR DESCRIPTION
**Pull request by alyssawilk**
This should fix the issue where the router gets a watermark event before it has stats
(onAboveWriteBufferHighWatermark before decodeHeaders())
This can happen on muxed H2 where one stream's response causes a high watermark event while another stream is parsing large headers.

The fix also addresses passing on high watermark events to the new downstream stream in case of retries.

part of #150 
Fixes #1447
Fixes #1443

### CODE REVIEW

**Comment by mattklein123** [comment]
@alyssawilk thanks for looking into this. This is definitely the crash we saw (I checked core dump). I'm struggling a bit with whether to fix this in router, or via combination of router and connection manager. I feel like we may have this problem in other filters in the future. One random thought: What if we allowed removing watermark callbacks, and when installing watermark callbacks, we fire high watermark right away if above? (Maybe that is already happening not sure). Then in router we would just install watermark when we know there is upstream, and delete when upstream goes away? 

This would be slightly less performing for callback add/remove, but at same time I think might be simpler? WDYT?

**Comment by mattklein123** [comment]
I guess what I'm suggesting is switching `void onDecoderFilterAboveWriteBufferHighWatermark()` etc. to opt-in variants like you have in other PR, and auto firing them in when callbacks are installed if applicable. Anyway just a thought.

**Comment by alyssawilk** [comment]
For this one I believe the complexity will only be in the router - it's the only entity which needs to be informed when the client downstream backs up because it has the handle on the upstream connection.

We could put the logic in the connection manager but I don't think it reduces complexity much.  The router (or someone?) still has to undo the readDisable()s on unregistration.  The connection manager it would have to maintain counter state, the router would still have some complexity (have to subscribe and unsubscribe on various retry events) we'd have to make callback removal safe while looping through connection manager callbacks.   That all said I'd be happy to take a whack at it Monday if you prefer it.

**Comment by alyssawilk** [comment]
Argh, on second thought you're right - we may need to keep the counts in the connection manager to ensure routers created after a back-up get the right count.  Feel free to roll back the original change and I'll send a fix Monday/Tuesday

**Comment by mattklein123** [comment]
I was mostly thinking if we end up with other filters that need to do back pressure, it's nice to have in connection manager anyway. Also if we think that very few filters will use the callbacks, we might also consider making them opt-in per above. 

We've only seen 1 crash with quite a bit of traffic so I don't think we need to revert. We can just fix next week. (I will revert if it gets worse for some reason).

**Comment by alyssawilk** [comment]
v2.  not terribly cleaned up but worth a high level pass if you think this is the right direction and feel free to tell me I need to do a vector for the callbacks now rather than leaving it TBD :-P

**Comment by mattklein123** [comment]
Cool thanks. TBH I'm running low on sleep so I will take a more thorough look tomorrow morning when I am better able to focus on this. :)

File: include/envoy/http/filter.h [hunk 1]
```diff
@@ -218,8 +218,22 @@ class StreamDecoderFilterCallbacks : public virtual StreamFilterCallbacks {
   /**
    * This routine can be called by a filter to subscribe to watermark events on the downstream
    * stream and downstream connection.
+   *
+   * Immediately after subscribing, the filte will get a high watermark callback for each
```
Comment (htuch) [inline include/envoy/http/filter.h]: Nit: s/filte/filter/

File: include/envoy/http/filter.h [hunk 2]
```diff
@@ -218,8 +218,22 @@ class StreamDecoderFilterCallbacks : public virtual StreamFilterCallbacks {
...
+   * outstanding backed up buffer.
    */
   virtual void addDownstreamWatermarkCallbacks(DownstreamWatermarkCallbacks& callbacks) PURE;
+
+  /**
+   * This routine can be called by a filter to stop subscribing to watermark events on the
+   * downstream stream and downstream connection.
+   *
+   * It is not save to call this from under the stack of a DownstreamWatermarkCallbacks callback.
```
Comment (htuch) [inline include/envoy/http/filter.h]: Nit: s/save/safe/

File: source/common/http/conn_manager_impl.cc [hunk 3]
```diff
@@ -1074,6 +1077,26 @@ void ConnectionManagerImpl::ActiveStreamDecoderFilter::
...
 }
 
+void ConnectionManagerImpl::ActiveStreamDecoderFilter::addDownstreamWatermarkCallbacks(
+    DownstreamWatermarkCallbacks& watermark_callbacks) {
+  // This is called exactly once per stream, by the router filter.
+  // If there's ever a need for another filter to subscribe to watermark callbacks this can be
+  // turned into a vector.
+  ASSERT(parent_.watermark_callbacks_ == nullptr);
+  parent_.watermark_callbacks_ = &watermark_callbacks;
+  for (uint32_t i = 0; i < parent_.high_watermark_count_; ++i) {
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: I think this is not right? We only fire callbacks if we are currently above high watermark? (I think you know this via high_watermark_count_ but might not have plumbed it through yet).

File: source/common/http/conn_manager_impl.cc [hunk 4]
```diff
@@ -1074,6 +1077,26 @@ void ConnectionManagerImpl::ActiveStreamDecoderFilter::
...
+    watermark_callbacks.onAboveWriteBufferHighWatermark();
+  }
+}
+void ConnectionManagerImpl::ActiveStreamDecoderFilter::removeDownstreamWatermarkCallbacks(
+    DownstreamWatermarkCallbacks& watermark_callbacks) {
+  ASSERT(parent_.watermark_callbacks_ == &watermark_callbacks);
+  for (uint32_t i = 0; i < parent_.high_watermark_count_; ++i) {
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: See below for other comment, but I think there will be lifetime issues if doing this in the removal case. Do we even need to fire below watermark callbacks here (and again would need to check if we are even above)? (I'm actually not totally sure of follow on implications into the connection pool, would need to think about this very deeply).

File: source/common/router/router.cc [hunk 5]
```diff
@@ -778,5 +763,37 @@ ProdFilter::createRetryState(const RetryPolicy& policy, Http::HeaderMap& request
...
+  request_encoder_ = &request_encoder;
+  // Now that there is an encoder, have the connection manager inform the manager when the
+  // downstream buffers are overrun.  This may result in immediate watermark callbacks referencing
+  // the encoder.
+  parent_.callbacks_->addDownstreamWatermarkCallbacks(downstream_watermark_manager_);
+}
+
+void Filter::UpstreamRequest::clearRequestEncoder() {
+  // Before clearing the encoder, unsubscribe from callbacks.  This may result
+  // in some clean up calls to onBelowWriteBufferLowWatermark which reference
```
Comment (mattklein123) [inline source/common/router/router.cc]: I think this is risky and needs a lot of thinking. Cleanup may/will occur in the normal reset/end_stream case at which point we need to consider the stream dead. It's possible this is safe because of your new guards in the codec helper, but I think this needs careful thought and testing.

Comment (alyssawilk) [inline source/common/router/router.cc]: For HTTP2 it's fine to consider the stream dead when it's reset and not update flow control - the H2 layer will take care of making sure all the stream data is consumed.

For HTTP/1 I assume we reuse connections and so we either need to read-enable in the router, or we need to re-enable somewhere else to make sure the next user of an upstream connection doesn't pick up a Network::Connection which won't be read from.

File: source/common/http/conn_manager_impl.cc (hunk 3 above)
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc]: I think this is right. 

Imagine a H2 connection where the Network::Connection gets backed up.  in callHighWatermarkCallbacks you inform all active streams, and track that the overall unit of the H2 connection is read-disabled.

Now you create a new stream and associate it with a new upstream connection, you need to get it in sync with all the other streams by calling readDisable the correct number of times.   If it's not blocked, you don't need to do anything.

Meanwhile if that connection wraps up and the upstream connection is disassociated in a way that can be reused (HTTP), you need to unravel the readDisables somewhere (I chose here for consistency but we could do it where the connection is disassociated or re-associated with another request.

Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: Sorry, you are right. I read this wrong the first time (for some reason I though we were iterating through all the streams here, never mind!). I might drop in a comment specific to the iteration talking about how we need to indicate above high watermark 0 or more times.

File: source/common/router/router.cc (hunk 5 above)
Comment (mattklein123) [inline source/common/router/router.cc]: For HTTP/1 we reuse connections IFF the the response was complete (otherwise we destroy the connection). (Standard HTTP/1 conn pool semantics). Since you do the clear/cleanup inline with either reset or end_stream, I think this is probably safe if you have the right guards during stack unwind, but honestly I'm not totally sure without looking at it more. It may end up being simpler to clean up disable inside the codec directly or in the codec client (whatever we end up doing please try to have as much symmetry as possible between HTTP/1 and HTTP/2 and upstream and downstream per some of my comments in the other PRs).

Either method is fine with me, I would just recommend trying to get tests that cause crashes (or assertion failures) with the stacks we have already seen in production.

File: source/common/http/codec_helper.h [hunk 6]
```diff
@@ -25,6 +34,7 @@ class StreamCallbackHelper {
       return;
     }
 
+    reset_callbacks_started_ = true;
```
Comment (mattklein123) [inline source/common/http/codec_helper.h]: Is it possible to just set reset_callbacks_run_ here and collapse into a single variable for simplicity? (Doesn't matter to me if you want to rename to reset_callbacks_started_). I think we don't have logic that requires the check to happen at the end?

File: source/common/http/http2/codec_impl.h [hunk 7]
```diff
@@ -265,11 +266,15 @@ class ClientConnectionImpl : public ClientConnection, public ConnectionImpl {
   // Propogate network connection watermark events to each stream on the connection.
   // The router will propogate it downstream.
   void onUnderlyingConnectionAboveWriteBufferHighWatermark() override {
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: Just to close the loop on this: What do you think about having the onUnderlying* functions for both server side and client side (so just move to base connection). This would unify the logic here vs. having part of it here and part of it in connection manager? I feel like that is easier to understand? No problem if you want to do that in different PR, but figured it's worth discussing since it impacts this change.

File: source/common/router/router.h [hunk 8]
```diff
@@ -192,6 +185,21 @@ class Filter : Logger::Loggable<Logger::Id::router>,
     void onPoolReady(Http::StreamEncoder& request_encoder,
                      Upstream::HostDescriptionConstSharedPtr host) override;
 
+    void setRequestEncoder(Http::StreamEncoder& request_encoder);
+    void clearRequestEncoder();
+
+    struct DownstreamWatermarkManager : public Http::DownstreamWatermarkCallbacks {
```
Comment (mattklein123) [inline source/common/router/router.h]: What's the reasoning behind having this be its own struct with parent ref? Can we just have this interface be implemented by UpstreamRequest?

File: test/integration/http2_upstream_integration_test.cc [hunk 9]
```diff
@@ -1,5 +1,7 @@
 #include "test/integration/http2_upstream_integration_test.h"
 
+#include <iostream>
```
Comment (mattklein123) [inline test/integration/http2_upstream_integration_test.cc]: nit: is this needed?

File: test/mocks/http/mocks.h [hunk 10]
```diff
@@ -258,6 +259,7 @@ class MockStreamDecoderFilterCallbacks : public StreamDecoderFilterCallbacks,
   MOCK_METHOD1(encodeTrailers_, void(HeaderMap& trailers));
 
   Buffer::InstancePtr buffer_;
+  std::list<DownstreamWatermarkCallbacks*> callbacks_{};
```
Comment (mattklein123) [inline test/mocks/http/mocks.h]: Since we don't currently support list/vector in real code should we do it here? Perhaps switch with pointer and appropriate asserts?

File: source/common/http/codec_helper.h (hunk 6 above)
Comment (alyssawilk) [inline source/common/http/codec_helper.h]: Ah, I didn't know if there was some need to be called after and figured better safe than sorry.  will collapse.

File: source/common/router/router.h (hunk 8 above)
Comment (alyssawilk) [inline source/common/router/router.h]: The Http::StreamCallbacks and the DownstreamWatermarkCallbacks have the same names.  I could rename one of them?

Comment (mattklein123) [inline source/common/router/router.h]: That's fine was just curious. Whatever you think is best.

File: source/common/http/conn_manager_impl.cc (hunk 4 above)
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc]: Yeah, I'm concerned about this too.

So let's say we get rid of it.  For the H2 case, it's entirely possible that an individual stream gets deleted without undoing its readDisables().  Since readDisable results in not consuming window and we have safeguards to consume when the stream is closed we're OK.  

I'm unsure of the logical place to do the same for HTTP though.  We'd need to make sure that if upstream sent a ton of data, blocking the downstream socket, the upstream connection was done and detached and reused, it wouldn't stay write blocked.  Can you suggest somewhere to make sure we don't end up assigning a non-reading Network::Connection to another request?

File: source/common/router/router.cc (hunk 5 above)
Comment (alyssawilk) [inline source/common/router/router.cc]: Hm, what if unsubscribe took an argument for unwinding?    We could call unsubscribe(unwind=true) onRequestComplete() and unsubscribe(unwind=false) in all other cases.

H2 will sort itself out in the codec if a stream is simply reset so the only case we really have to worry about is HTTP reused connections which should have onRequestComplete, right?

File: source/common/http/codec_helper.h (hunk 6 above)
Comment (mattklein123) [inline source/common/http/codec_helper.h]: I think one of the variables still needs to be deleted? Will keep reviewing otherwise.

File: source/common/http/conn_manager_impl.cc [hunk 11]
```diff
@@ -173,6 +173,9 @@ StreamDecoder& ConnectionManagerImpl::newStream(StreamEncoder& response_encoder)
   new_stream->response_encoder_ = &response_encoder;
   new_stream->response_encoder_->getStream().addCallbacks(*new_stream);
   config_.filterFactory().createFilterChain(*new_stream);
+  if (underlying_connection_above_high_watermark_) {
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: Is this actually needed? Won't the callbacks fire when the filter registers for callbacks later? I'm wondering if we can kill underlying_connection_above_high_watermark_ variable entirely?

File: source/common/http/conn_manager_impl.h [hunk 12]
```diff
@@ -290,14 +290,16 @@ class ConnectionManagerImpl : Logger::Loggable<Logger::Id::http>,
   void onEvent(Network::ConnectionEvent event) override;
   // Pass connection watermark events on to all the streams associated with that connection.
   void onAboveWriteBufferHighWatermark() override {
-    for (ActiveStreamPtr& stream : streams_) {
-      stream->callHighWatermarkCallbacks();
-    }
+    ASSERT(codec_);
```
Comment (mattklein123) [inline source/common/http/conn_manager_impl.h]: nit: this will crash in an obvious way a few lines later so I would kill this assert. Same below.

File: source/common/http/http2/codec_impl.h [hunk 13]
```diff
@@ -84,6 +84,17 @@ class ConnectionImpl : public virtual Connection, Logger::Loggable<Logger::Id::h
   Protocol protocol() override { return Protocol::Http2; }
   void shutdownNotice() override;
   bool wantsToWrite() override { return nghttp2_session_want_write(session_); }
+  // Propogate network connection watermark events to each stream on the connection.
+  void onUnderlyingConnectionAboveWriteBufferHighWatermark() override {
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: Just for a public record of our IM conversation, it is possible that we kill onUnderlying* functions entirely and just have codec also register for connection callbacks. I don't feel strongly about it one way or the other (though I think it might simplify code further), but just pointing it out.

File: source/common/http/http2/codec_impl.cc [hunk 14]
```diff
@@ -62,7 +62,7 @@ ConnectionImpl::StreamImpl::StreamImpl(ConnectionImpl& parent, uint32_t buffer_l
   }
 }
 
-ConnectionImpl::StreamImpl::~StreamImpl() { ASSERT(unconsumed_bytes_ == 0); }
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc]: Q: What's the case in which this assert no longer holds true? nit: Can you delete empty destructor?

File: source/common/http/http2/codec_impl.h [hunk 15]
```diff
@@ -175,6 +186,7 @@ class ConnectionImpl : public virtual Connection, Logger::Loggable<Logger::Id::h
     int32_t stream_id_{-1};
     uint32_t unconsumed_bytes_{0};
     uint32_t read_disable_count_{0};
+    uint32_t underlying_connection_above_watermark_count_{0};
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: unused?

File: source/common/router/router.cc [hunk 16]
```diff
@@ -780,5 +765,37 @@ ProdFilter::createRetryState(const RetryPolicy& policy, Http::HeaderMap& request
...
+  // The downstream connection is overrun.  Pause reads from upstream.
+  parent_.parent_.cluster_->stats().upstream_flow_control_paused_reading_total_.inc();
+  parent_.request_encoder_->getStream().readDisable(true);
+}
+
+void Filter::UpstreamRequest::DownstreamWatermarkManager::onBelowWriteBufferLowWatermark() {
+  ASSERT(parent_.request_encoder_);
+  // The downstream connection has buffer available.  Resume reads from upstream.
+  parent_.parent_.cluster_->stats().upstream_flow_control_resumed_reading_total_.inc();
+  parent_.request_encoder_->getStream().readDisable(false);
```
Comment (mattklein123) [inline source/common/router/router.cc]: I just looked through code again and I'm still not entirely convinced that this is correct. Are you able to this this case in tests and cause a call through to https://github.com/lyft/envoy/blob/master/source/common/http/http2/codec_impl.cc#L144 ? I'm just trying to work through whether this is safe or not. Part of me wonders whether `nghttp2_session_consume` actually fails silently here. Should we add an assert to that? If you have sorted through this can you add more comments on why this is safe in the reset/end_stream case?

File: source/common/http/conn_manager_impl.cc (hunk 11 above)
Comment (alyssawilk) [inline source/common/http/conn_manager_impl.cc]: There's 2 ways things can be delayed

You can have the connection get blocked when you have a stream but no upstream connection.
At this point you get informed when the router registers.  But you can also have the connection get blocked before the stream is *created*.  This handles that case.  We tell the stream it's blocked and it remembers to tell the router later.

File: source/common/http/http2/codec_impl.h (hunk 13 above)
Comment (alyssawilk) [inline source/common/http/http2/codec_impl.h]: I kind of like everything passing through the connection manager as the authority of client side connections but maybe that's just me?

File: source/common/http/conn_manager_impl.cc (hunk 11 above)
Comment (mattklein123) [inline source/common/http/conn_manager_impl.cc]: Ah I see. OK. Can you add comments here? I think in general more comments would be useful in cases like this.

File: source/common/http/http2/codec_impl.cc (hunk 14 above)
Comment (alyssawilk) [inline source/common/http/http2/codec_impl.cc]: Oh yeah, I meant to call that out.

So it's possible for the entire connection to get torn down with open streams.  In this case there's really no way to consume. The only way to add this assert back in would be to loop through streams there before they're deleted in ~ConnectionImpl and zero it out and that seemed overkill.

File: source/common/http/http2/codec_impl.h (hunk 13 above)
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: I could go either way. On one hand I agree, on the other hand, the other approach would put logic closer to where it is actually needed. I would just leave it for now if you are happy with it.

File: source/common/http/http2/codec_impl.cc (hunk 14 above)
Comment (mattklein123) [inline source/common/http/http2/codec_impl.cc]: OK I see. I might just add a comment in the empty destructor.

File: source/common/router/router.cc (hunk 16 above)
Comment (alyssawilk) [inline source/common/router/router.cc]: Sounds like you'd prefer the route where the codec handles things.   H2 already does and I can fix up HTTP to do so in that PR.  My concern is if we're wrong here there will be crashes but if we're wrong there there will be slow silent blackholes which are harder to debug.

Comment (mattklein123) [inline source/common/router/router.cc]: I don't really have a preference, I just want to feel confident that it works. :)

With the code you have now, are you able to hit the http/2 read enable / consume case? If so, does it still work if you check the RC of consume w/ assert?

Comment (alyssawilk) [inline source/common/router/router.cc]: So the current version you're looking at no longer calls readDisable on teardown.  I instead updated the docs to say that it should be handled in the codec.

Checking out a prior version it's super duper hard to verify this in a unit test.    The codec test has this thing where all data is flushed immediately so if you readEnable the peer you end up under the stack of the framer twice and it's not reentrant and things crash with very confusing traces (not that I spent 6h debugging that one week).  The router doens't have actual buffer in these tests and I don't trust it to have real communication with the codec.

What I did was check out the old code where we readEnable on reset, stuck a boolean guard set true during runResetCallbacks and verified my integration test occasionally consumes  data under the stack of runResetCallbacks (it does) and with rc == 0 (it does).  That doesn't mean every type of disconnect and reset would work, but it does show that that particular one does.

Comment (mattklein123) [inline source/common/router/router.cc]: > The codec test has this thing where all data is flushed immediately

FYI it doesn't have to be this way I don't think (I'm not exactly sure which flushing you are talking about), but it might be too much work to setup the mocks to do what you want.

> What I did was check out the old code where we readEnable on reset, stuck a boolean guard set true during runResetCallbacks and verified my integration test occasionally consumes data under the stack of runResetCallbacks (it does) and with rc == 0 (it does). That doesn't mean every type of disconnect and reset would work, but it does show that that particular one does.

OK. So which version do you prefer? The current code? Or what you had before? I'm fine either way, just want to know what to review. :)

Comment (alyssawilk) [inline source/common/router/router.cc]: I don't have strong feelings either so unless you have a preference we can go with this.

File: source/common/http/http2/codec_impl.h [hunk 17]
```diff
@@ -265,11 +275,15 @@ class ClientConnectionImpl : public ClientConnection, public ConnectionImpl {
   // Propogate network connection watermark events to each stream on the connection.
   // The router will propogate it downstream.
   void onUnderlyingConnectionAboveWriteBufferHighWatermark() override {
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: Can we push all this logic into base Connection class? Do we need to override in client? Seems like booleans and asserts would still be useful in the base class and then we can collapse the duplicate code?

File: source/common/router/router.cc [hunk 18]
```diff
@@ -780,5 +765,37 @@ ProdFilter::createRetryState(const RetryPolicy& policy, Http::HeaderMap& request
...
+  request_encoder_ = &request_encoder;
+  // Now that there is an encoder, have the connection manager inform the manager when the
+  // downstream buffers are overrun.  This may result in immediate watermark callbacks referencing
+  // the encoder.
+  parent_.callbacks_->addDownstreamWatermarkCallbacks(downstream_watermark_manager_);
+}
+
+void Filter::UpstreamRequest::clearRequestEncoder() {
+  // Before clearing the encoder, unsubscribe from callbacks.  This may result
+  // in some clean up calls to onBelowWriteBufferLowWatermark which reference
```
Comment (mattklein123) [inline source/common/router/router.cc]: this comment is out of date now right?

File: source/common/http/http2/codec_impl.h [hunk 19]
```diff
@@ -84,6 +84,17 @@ class ConnectionImpl : public virtual Connection, Logger::Loggable<Logger::Id::h
   Protocol protocol() override { return Protocol::Http2; }
   void shutdownNotice() override;
   bool wantsToWrite() override { return nghttp2_session_want_write(session_); }
+  // Propogate network connection watermark events to each stream on the connection.
+  void onUnderlyingConnectionAboveWriteBufferHighWatermark() override {
+    for (auto& stream : active_streams_) {
+      stream->runHighWatermarkCallbacks();
+    }
+  }
+  void onUnderlyingConnectionBelowWriteBufferLowWatermark() override {
```
Comment (mattklein123) [inline source/common/http/http2/codec_impl.h]: We can delete these definitions below in ClientConnection now, right? I think  they are just duplicate overrides. Also, love the changer to push over watermark tracking into connection class. Much cleaner! :)

File: source/common/http/codec_helper.h [hunk 20]
```diff
@@ -40,7 +48,14 @@ class StreamCallbackHelper {
     callbacks_.reserve(8);
   }
 
-  void addCallbacks_(StreamCallbacks& callbacks) { callbacks_.push_back(&callbacks); }
+  void addCallbacks_(StreamCallbacks& callbacks) {
+    callbacks_.push_back(&callbacks);
+    if (!reset_callbacks_started_) {
```
Comment (mattklein123) [inline source/common/http/codec_helper.h]: Does this actually happen? I feel like adding callbacks after reset is broken if it's happening. If this is just to have symmetry with other checks but doesn't happen can we switch to ASSERT?

**Comment by mattklein123** [comment]
@alyssawilk I just reviewed this again and other than the comment I just added and the one about deleting the duplicate overrides this LGTM. @htuch or @dnoe if you feel like going through this for a quick sanity check tomorrow morning, it's probably a good idea since this is really quite complicated and better to have more eyes.

File: source/common/http/codec_helper.h [hunk 21]
```diff
@@ -56,7 +70,8 @@ class StreamCallbackHelper {
 
 private:
   std::vector<StreamCallbacks*> callbacks_;
-  bool reset_callbacks_run_{};
+  bool reset_callbacks_started_{};
+  uint32_t high_watermark_callbacks_{0};
```
Comment (htuch) [inline source/common/http/codec_helper.h]: Nit: prefer consistent default brace initialization style.

File: source/common/http/conn_manager_impl.cc [hunk 22]
```diff
@@ -173,6 +173,10 @@ StreamDecoder& ConnectionManagerImpl::newStream(StreamEncoder& response_encoder)
   new_stream->response_encoder_ = &response_encoder;
   new_stream->response_encoder_->getStream().addCallbacks(*new_stream);
   config_.filterFactory().createFilterChain(*new_stream);
+  // Make sure new streams are appraised that the underlying connection is blocked.
```
Comment (htuch) [inline source/common/http/conn_manager_impl.cc]: Nit: s/appraise/apprise/

File: source/common/http/http2/codec_impl.cc [hunk 23]
```diff
@@ -747,6 +747,10 @@ ClientConnectionImpl::ClientConnectionImpl(Network::Connection& connection,
 Http::StreamEncoder& ClientConnectionImpl::newStream(StreamDecoder& decoder) {
   StreamImplPtr stream(new ClientStreamImpl(*this, per_stream_buffer_limit_));
   stream->decoder_ = &decoder;
+  // If the connection is currently above the high watermark, make sure to inform the new stream.
+  if (connection_.aboveHighWatermark()) {
```
Comment (htuch) [inline source/common/http/http2/codec_impl.cc]: Did you consider doing a similar add/remove callback dance as done at the stream level but at the connection level? Could the approach here have been used at the stream level?

File: source/docs/flow_control.md [hunk 24]
```diff
@@ -220,27 +236,44 @@ The low watermark path is as follows:
...
- * `Envoy::Http::Http2::ConnectionImpl::onBelowWriteBufferLowWatermark()`
-   calls `ConnectionManagerImpl::ActiveStream::callLowWatermarkCallbacks()` on all
-   `ActiveStreams` on the connection.
+ * `Envoy::Http::Http2::ConnectionManagerImpl::onBelowWriteBufferHighWatermark()`
+   calls `ConnectionImpl::onUnderlyingConnectionBelowWriteBufferHighWatermark()`
+   on `codec_`.
+ * When `Envoy::Http::Http2::ConnectionImpl` receives `onBelowWriteBufferHighWatermark()` it calls
+   `runHighWatermarkCallbacks()` for each stream of the connection.
+ * When `ConnectionManagerImpl::ActiveStream::onBelowWriteBufferHighWatermark()` is
+   called it calls `ConnectionImpl::ActiveStream::callHighWatermarkCallbacks()`
```
Comment (htuch) [inline source/docs/flow_control.md]: Is there some High/Low copy+paste snafu in this point and the above one?

File: source/docs/flow_control.md [hunk 25]
```diff
@@ -87,7 +87,14 @@ the downstream conection.  It passes events to the router filter via
...
 "number of streams * number of filters" callbacks.  Instead, only the router
-filter is notified and only the "number of streams" multiplier applies.
+filter is notified and only the "number of streams" multiplier applies.  Because
+the router filter only subscribes to notifications when it has an upstream
+connection, the connection manager tracks how many outstanding high watermark
+events have occurred and passes any on to the router filter when it subscribes.
+
+It is worth noting that the router does not unwind `readDisable(true)` calls on
+destruction.  The codecs are responsible for tracking that a given stream no
+longer contributes to the read blocked state and unwinding.
```
Comment (htuch) [inline source/docs/flow_control.md]: No need to modify PR, but can you explain how this unwinding is happening above?

File: source/common/http/http2/codec_impl.cc (hunk 23 above)
Comment (alyssawilk) [inline source/common/http/http2/codec_impl.cc]: Unfortunately can't - unlike the filter level callbacks, there's only ever one subscriber to the Network::Connection callbacks so the connection doesn't know when new streams are created.

We could move this from here to codec_helper addBacllbacks() to be a bit more parallel if you prefer

Comment (htuch) [inline source/common/http/http2/codec_impl.cc]: No strong preference, just wondering about the rationale for different models (callback vs. track-and-check). Fine as is.

Comment (htuch) [inline source/common/http/http2/codec_impl.cc]: Maybe just add a comment explaining this choice there for programmer archaeologists of the future.

File: source/docs/flow_control.md (hunk 24 above)
Comment (alyssawilk) [inline source/docs/flow_control.md]: Nice catch - Missed a /g on my search-and-replace :-)
