### PR TITLE
Fix segfault caused by modifying list within iteration.

### LINKED ISSUE #903: Bad SDS Host URL causes seg fault
If an unresolvable URL is specified in the Cluster Manger SDS Hosts URL, a Segmentation fault will be raised without any helpful error text, even at a debug log level.

Below is an example `Dockerfile` and `front-envoy.config` for repro. Replacing `tcp://does-not-exist.amazonaws.com:80` with a valid SDS host resolves the issue.

**Dockerfile**
```sh
FROM lyft/envoy:latest

COPY ./front-envoy.json /etc/front-envoy.json

CMD /usr/local/bin/envoy -c /etc/front-envoy.json -l debug
```

**front-envoy.json**
```json
{
  "listeners": [
    {
      "address": "tcp://0.0.0.0:80",
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "ingress_http",
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],
                  "routes": [
                    {
                      "timeout_ms": 0,
                      "prefix": "/",
                      "cluster": "service_echo"
                    }
                  ]
                }
              ]
            },
            "filters": [
              { "type": "both", "name": "health_check",
                "config": {
                  "pass_through_mode": false, "endpoint": "/healthcheck"
                }
              },
              {
                "type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "access_log_path": "/dev/null",
    "address": "tcp://0.0.0.0:8001"
  },
  "cluster_manager": {
    "sds": {
      "cluster": {
        "name": "sds",
        "connect_timeout_ms": 250,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [{"url": "tcp://does-not-exist.amazonaws.com:80"}]
      },
      "refresh_delay_ms": 3000
    },
    "clusters": [
      {
        "name": "service_echo",
        "connect_timeout_ms": 250,
        "type": "sds",
        "service_name": "echoer",
        "lb_type": "round_robin",
        "health_check":  {
          "type": "http",
          "timeout_ms": 2000,
          "interval_ms": 5000,
          "interval_jitter_ms": 5000,
          "unhealthy_threshold": 2,
          "healthy_threshold": 2,
          "path": "/",
          "service_name": "echoer"
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by dnoe**
A segfault arose when iterating over the list of
secondary_init_clusters_ and calling initialize().  The call to
initialize may result in the initialized item being removed from the
secondary_init_clusters_ list while walking through the list.  The
initialized item can only remove itself, not any other item in the
list.  However, this resulted in chasing an invalidated iterator when
trying to go to the next element in the list.

To fix this the loop is modified so that the iterator is advanced to the
next item (or end() if no more items) before calling
Cluster::initialize().

A test is included which exercises this scenario

Fixes #903

### CODE REVIEW

File: test/common/upstream/cluster_manager_impl_test.cc [hunk 1]
```diff
@@ -838,4 +838,33 @@ TEST(ClusterManagerInitHelper, AddSecondaryAfterSecondaryInit) {
...
+TEST(ClusterManagerInitHelper, RemoveClusterWithinInitLoop) {
+  InSequence s;
+  ClusterManagerInitHelper init_helper;
+
+  // Tests the scenario encountered in Issue 903: The cluster was removed from
+  // the secondary init list while traversing the list.
+  NiceMock<MockCluster> cluster;
+  // Fake that we are in the secondary InitializePhase for this test.
+  ON_CALL(cluster, initializePhase()).WillByDefault(Return(Cluster::InitializePhase::Secondary));
+  // We expect that initialize() should be called first upon addCluster.  In the
```
Comment (mattklein123) [inline test/common/upstream/cluster_manager_impl_test.cc]: The code change looks good (thanks for fixing), but I think the test and the explanation can be simplified a bit. For secondary clusters, initialize() is not called when addCluster() is called. It's called once all the primary clusters have initialized OR when static load completes if there are no primary clusters. So, I would rejigger this test to do:

```
ON_CALL(cluster, initializePhase())...
init_helper.addCluster(cluster);
EXPECT_CALL(cluster, initialize())... // remove inline
init_helper.onStaticLoadComplete();
```

Then also simplify the explanation surrounding the test.

Comment (dnoe) [inline test/common/upstream/cluster_manager_impl_test.cc]: OK, thanks! This is definitely useful.  I will ensure the rejiggered test fails with the original code, and passes with the fix.
